### ISSUE TITLE
Tweaking the post content

### ISSUE THREAD

**Issue by svnsbck** [dshanske/indieweb-post-kinds#105]
Hi! I was just wondering if it is possible to tweak the generated output to one's liking. Or better: if it's possible, where would I do that?
Idea here is for example if I post a **Reply** to have the syntax say:
In reply to:
*title of post*
Author

I can adjust some things easily in CSS but where I could I adjust the generated text?

Any help appreciated, all the best and thanks for the all the work. Just getting into the Indieweb thing, and enjoying it a lot.

**Comment by miklb** [comment]
@svnsbck you can create your own kind template in your theme. You can view the default templates in the plugin directory, copy/edit them in a `kind_views/kind-reply.php` in your theme.

**Comment by svnsbck** [comment]
Ah, cool! Thanks a lot. Will try to implement that!

**Comment by dshanske** [comment]
Closed as implemented already
