### ISSUE TITLE
Emojis in Post Kinds prevent data retention

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#117]
When I try to reply to 
https://mastodon.social/@chrisaldrich/98885605265821060 the retrieve button works well and returns the appropriate data, but when attempting to either save a draft or publish the post, the data in the Post Properties meta box disappears.

I'm guessing that a filter somewhere is seeing the pineapple emoji in the Author field and purging (or not saving) all of the data in the entire meta box (except for the Permalink).

**Comment by dshanske** [comment]
I can't reproduce this in the new version.
