### ISSUE TITLE
Errors with "read" post kind

### ISSUE THREAD

**Issue by interllectual** [dshanske/indieweb-post-kinds#120]
Getting fatal errors when using post kind of read. Commenting out lines 92-97 in indieweb-post-kinds/includes/views/kind.php fixes the issue. 

(just started using this plugin, thank you for all your work on this!)

**Comment by dshanske** [comment]
I introduced a few bugs in the last version. Expect fixes coming in the next day.

**Comment by dshanske** [comment]
@interllectual  Out of curiosity, what prompted you to start using it? Always looking for ways to make it better.

**Comment by interllectual** [comment]
I am long-timer in the web standards crowd and have been following indieweb for a long time. I have taken a break from my personal site for a variety of life reasons, and just recently decided to take the time to get back into it. Trying to own my data while still having a manageable workflow is my focus right now.

**Comment by dshanske** [comment]
This should be fixed with the latest commit, but not yet pushed to the wordpress.org repository.
