### ISSUE TITLE
Weird offset errors

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#122]
I get these errors for two items as mentioned in Slack.

Line 18 error when I have a featured image for a post.

Line 93 occured when I add a started/finished data to a read kind post.

Notice: Undefined offset: -1 in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 18

Notice: Undefined offset: -1 in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 18

A Game of Ghosts by John Connolly Notice: Undefined variable: meta in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/views/kind.php on line 93 Fatal error: Call to a member function get_duration() on a non-object in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/views/kind.php on line 93

**Comment by dshanske** [comment]
These errors were fixed in the latest commit.

**Comment by xavierroy** [comment]
Is this an errant leftover? I removed this and some errors vanished.

https://github.com/dshanske/indieweb-post-kinds/blob/f9aeac76ea50d3a22644c4af245cdbc620648dac/includes/views/kind.php#L117
