### ISSUE TITLE
Feature Idea: Widget for "Last seen"

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#124]
This is something for either Post Kinds or Simple Location.

It would be cool if one or the other of the plugins supported a widget that pulled the data for one's last checkin and displayed it on one's home page as an "XXX was last seen at" feature (especially for people whose home pages aren't their post streams). 

There are some examples of this type of "Last seen at" type of functionality out there. Here are some that I've come across in the last day or so:
* aaronpk: Checked in at box on homepage https://aaronparecki.com/
* Sebastiaan Andeweg has a last seen at on https://seblog.nl/
* Amy has a version of this (and other "lasts" if you wanted to extend the widget to other categories for Post Kinds, in which case then definitely it's a Post Kinds feature instead of Simple Location) at https://rhiaro.co.uk/

I think most of the infrastructure is already built, it would be nice to have it displayed/used in other places (like sidebars, footers, etc. that widgets can use).

**Comment by dshanske** [comment]
Simple Location supports location for users, posts, comments and terms. Users and terms are supported but not implemented.

**Comment by dshanske** [comment]
I would want to have this in Simple Location and just have Post Kinds trigger the update.

**Comment by dshanske** [comment]
https://github.com/dshanske/simple-location/issues/25

**Comment by dshanske** [comment]
Closing as implemented in Simple Location. If there is anything that Post Kinds can enhance...feel free to reopen.
