### ISSUE TITLE
Retrieve button fails on following sites:

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#125]
Thought I'd open an issue to collect sites on which the retrieve button fails for various reasons to catch data.

* https://twit.tv/shows/this-week-in-google/episodes/432 
** (doesn't pull in anything in any field except for Name/Title which shows "ERROR: The request could not be satisfied") All posts on this site seem to have this same issue

**Comment by dshanske** [comment]
At least it says something now. It used to say nothing. Will analyze

**Comment by dshanske** [comment]
This appears to be an issue with the user agent. They are forbidding access. I adjusted the user agent. It is still readable by a human though. Also, added support in the last commit to pull video and audio tags from the page as well as looking through the URLs on the page for video/audio files.

**Comment by dshanske** [comment]
One of the words they are filtering on is WordPress, which is disturbing. It is also giving a 403.. would have appreciated something more developer helpful.
