### ISSUE TITLE
Taxonomy mismatch between admin UI for settings and archive page displays

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#126]
In class-kind-taxonomy.php there's a somewhat dissonant mismatch between what appears in the Admin UI for Post Kinds settings and what appears on the archive pages which are presented to readers.

While having the settings page indicate than an "Article" is "traditional long form content: a post with an explicit title and body" makes more sense to the (especially new post kinds user and) site owner to help them choose which kinds to use and display, it's not necessarily the best UI to show to a reader of the site who won't care as much about the specifics of the semantics.

as an example, compare:
https://david.shanske.com/kind/article/
http://boffosocko.com/kind/article/

I'd suggest maybe having an additional line in each of the `$kinds = array` fields to help differentiate between the two--ie add something like an `'archive-description' =>` line so the shown text can be modified. (I think the 'description' currently only appears in the two places I mentioned, but I may be wrong.)

To help out below are some reasonable generic suggestions for each of the types for a better site reader description, (most are predicated on the context being the archives for these post types):

article: Long form content
note: Short content: a microblog of status updates or short notes
reply: Replies to content typically on another site
repost: Reposts of content from other sites
like: Compliments to the original post/poster of external content
favorite: Bookmarks of special significance
bookmark:Interesting Links/bookmarks for personal use or sharing with others
photo: Posts with an embedded image/photo
video: Posts with embedded video
audio: Posts with embedded audio files
tag: Posts tagged as being of a specific category or tag, or for person tagging
rsvp: Responses to event invitations
listen: Playlist of posts listened to, or scrobbled
watch: Playlist of watched movies, television shows, online videos, and other visual-based events
checkin: Geographic locations visited
wish: Wishlist
play: List of games played
weather: Weather conditions experienced
exercise: Workouts
trip: List of journeys
itinerary: Parts of scheduled trips including transit by car, plane, train, boat, bicycle, etc.
eat: Food diary
drink: Food diary of items drunk
follow: Follow or Subscription list
jam: Playlist of personally meaningful songs
read: Reading list of books, magazines, newspaper articles, other physical documents, or online posts
quote: Quoted content
mood: Feelings, nothing more than feelings
recipe: Lists of ingredients and directions for making food or drink
issue: Issues filed related to source code, though potentially anything at a source control repository.
event: List of hosted events

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/126" class="u-in-reply-to"></a>Further to this and as a result of your post kinds session at IWC Austin, why not allow the user to personally write (or overwrite) the definitions of the UI readable parts so that they can create their own definitions of these things on their own sites. You can have placeholder text that a majority of people might agree with as a default, but by making it personally identify-able, you'll have solved part of your problem.)

**Comment by dshanske** [comment]
They can now...at least programmatically. But not in an interface

**Comment by dshanske** [comment]
They can now be edited if you put on debug mode, in the Taxonomy editor.
