### ISSUE TITLE
Multikind post support

### ISSUE THREAD

**Issue by acegiak** [dshanske/indieweb-post-kinds#13]
Posts that have multiple verbs/kinds are a common use case on several existing social networks and so for some people it is the most natural ux flow.

**Comment by dshanske** [comment]
I'm going to start this as an 'experimental' feature. To start, I'll be setting up a separate PHP file for any multikind functions and setting up a variable to disable the single kind chooser. Then I'll go through and see how the behavior of functions needs to change if it is multikind.

I want to make sure supporting another 'mode' or switching modes doesn't break anything.

**Comment by dshanske** [comment]
I'm closing this one for now. If a PR arrives that implements it, I will consider merging it, but it seems unlikely I will implement it myself.
