### ISSUE TITLE
can't publish after update to 2.7.4

### ISSUE THREAD

**Issue by interllectual** [dshanske/indieweb-post-kinds#131]
After updating to 2.7.4, I can’t publish with the plugin enabled. I have tried status, RSVP, and bookmark. After hitting publish, I get a 404 when I click on “view post”, and it doesn’t show on the main page of the site. When I disable the plugin everything works as expected. Also, when I try to retrieve data from urls where it worked previously, I get no response.

I can see one error related to post kinds in the logs:

[09-Dec-2017 22:41:33 UTC] PHP Notice:  Undefined offset: 1 in ~/wp-content/plugins/indieweb-post-kinds/includes/class-parse-this.php on line 742

The rest of the errors are all 
[09-Dec-2017 23:27:41 UTC] PHP Notice:  Undefined index: items in ~/wp-includes/rest-api/endpoints/class-wp-rest-settings-controller.php on line 328

I am getting many of these.

**Comment by dshanske** [comment]
The rest controller item shouldn't be something I did

**Comment by interllectual** [comment]
Just disabled all plugins but post kinds. Was able to publish a status, but not a bookmark, and was not able to retrieve info. No errors in log. Would cacheing by my host potentially affect this? I think I have turned it all off, but maybe that is not possible..

**Comment by miklb** [comment]
@interllectual is this happening with all URLs you are trying to retrieve info for, or a specific URL?

**Comment by interllectual** [comment]
All that I have tried so far, including ones that worked before, such as https://lostcoastoutpost.com/2017/dec/6/obituary-patricia-lynne-siering-1962-2017/ and http://time.com/time-person-of-the-year-2017-silence-breakers/?utm_campaign=time&utm_source=twitter.com&utm_medium=social&xid=time_socialflow_twitter

**Comment by dshanske** [comment]
https://tiny.n9n.us/2017/12/09/time-person-of-the-year-2017-the-silence-breakers/ - I just tried that on my test site....

**Comment by interllectual** [comment]
Strange. I thought it may be a browser issue, so I tried  switching browsers to no avail. I am getting this error in Chrome:

 Uncaught ReferenceError: response is not defined
    at Object.error (retrieve.js?ver=2.7.4:71)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.1:2)
    at Object.fireWith [as rejectWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.1:2)
    at y (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.1:4)
    at XMLHttpRequest.c (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.1:4)

**Comment by dshanske** [comment]
Errors? Haven't touched the file since the 2.7.0 update.

**Comment by interllectual** [comment]
Here is what I am seeing:

<img width="826" alt="screenshot" src="https://user-images.githubusercontent.com/450456/33807505-ddd8ac58-dda5-11e7-8abe-d37d82605ec4.png">

**Comment by miklb** [comment]
> Errors? Haven't touched the file since the 2.7.0 update.

I'm guessing these are JS linter errors.

**Comment by dshanske** [comment]
I have to start linting my JS? Another automation. Oh, well

**Comment by miklb** [comment]
Or lint as you go in your editor to start

**Comment by dshanske** [comment]
I use a text editor

**Comment by miklb** [comment]
I have a js linter setup in my theme's Travis I believe, I'll see if I can add it to the grunt task for the markdown files I'm already planning on working on.

**Comment by interllectual** [comment]
Fixed by turning off debug logs, as per https://chat.indieweb.org/wordpress/2017-12-12

**Comment by dshanske** [comment]
When the next version is merged, this won't be an issue even with DEBUG.
