### ISSUE TITLE
Variables passed by reference in Video Kind?

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#136]
Not sure what the issue is or may be, since I found this in the wild, but in case it's not otherwise reported and someone can puzzle out what happened:

The following post: http://xavierroy.com/2017/our-submission-for-the-dybgenesyschennai-contest/

Showed error:
`Strict Standards: Only variables should be passed by reference in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/views/kind-video.php on line 10 Notice: Undefined index: url in /hsphere/local/home/xavier/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/views/kind-video.php on line 15`

Incidentally, for fun, it's an example of someone running the TwentySixteen Indieweb Theme fork with some color modification and they've enabled Food and Drink post kinds.

**Comment by dshanske** [comment]
Should be fixed in 2.7.6
