### ISSUE TITLE
Likes from Quill show "Array" rather than url

### ISSUE THREAD

**Issue by interllectual** [dshanske/indieweb-post-kinds#137]
Not sure if this is a Post Kinds or micropub issue. Since version 2.7.5 update, liked tweets submitted through Quill show "Array" instead of url, see https://andreaarbogast.com/2017/12/20/16720/.

**Comment by dshanske** [comment]
I am aware.

**Comment by dshanske** [comment]
Working to get a PR into Micropub.

**Comment by dshanske** [comment]
Fixed in the latest development version of Micropub.
