### ISSUE TITLE
Only Add Photos to Photo Kind if not in Post Content

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#138]
Write function to avoid doubling photos if manually added to content.

**Comment by dshanske** [comment]
Basically, if [gallery or src="photourl" appears in the content, then don't auto-embed.

**Comment by stephenpieper** [comment]
Can I just bump this up a bit?

**Comment by dshanske** [comment]
I have implemented a variety of ways to try and address this.
