### ISSUE TITLE
Add support for custom post kinds

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#146]
There are more kinds listed at https://indieweb.org/posts. Are there plans to support them? I am using sleep right now as private posts.

**Comment by xavierroy** [comment]
Ok. In that case, can you add sleep and issue post kinds? For issues, see https://xavierroy.com/kind/issue/

**Comment by dshanske** [comment]
Issue is a reserved kind. I added it to the list for future development. I will add sleep for future as well. Not sure I'll write the UI for it. The reason I do it that way, is I can in theory, if someone writes a Micropub client, make it work without having something user editable yet. For example, food and drink sort of work with Teacup.
