### ISSUE TITLE
Duplicate photos in post when using 'photo' post-kind

### ISSUE THREAD

**Issue by raretrack** [dshanske/indieweb-post-kinds#147]
I have an issue when I use the photo post-kind in a WP post. 

When including a photo in a post and setting the post-kind to 'Photo' I find the photo is duplicated in the post - one larger version and one smaller version. This behaviour is the same whether I add the photo directly to the post, or first upload it to the media library.

Changing the post-kind to 'Note' removes the behaviour. 

(I also discussed this issue in the indieweb-wordpress chat room on Saturday 20 November.)

Here are two screenshots of a test post I did on WP.

'Photo':
![pk photo](https://user-images.githubusercontent.com/20622687/35191687-2d12521c-fe79-11e7-8b75-87226e23e9e2.png)

'Note':
![pk note](https://user-images.githubusercontent.com/20622687/35191689-3136582a-fe79-11e7-8a83-3bcc4a56163f.png)

**Comment by mrkrndvs** [comment]
@raretrack I have been experiencing the same thing. 

![](https://collect.readwriterespond.com/wp-content/uploads/2018/02/Screenshot-2018-02-12-at-10.14.46-AM.png)

It also seems to happen when I add audio too. 

![](https://collect.readwriterespond.com/wp-content/uploads/2018/02/Screenshot-2018-02-12-at-10.15.25-AM.png)

I inserted the image as 'Full' size. I think that you propobably defaulted to 'Medium'. I assume that the initial image is 'Full' too. 

I wonder if there is a way to 'hide' the inserted image and then it just shows the media content at the beginning of the post?

**Comment by dshanske** [comment]
I tried something in the current development version if you want to try it, but bear in mind some other big changes I am still refining.

**Comment by mrkrndvs** [comment]
Happy to test anything @dshanske if you need. Where do you store the 'development' version? If it is something you are aware of, I am also happy to just wait in line.

**Comment by dshanske** [comment]
The master branch of this repository

**Comment by dshanske** [comment]
I'm working on it here.

**Comment by dshanske** [comment]
I usually work in a branch, but didn't

**Comment by mrkrndvs** [comment]
@dshanske I just uninstalled 2.7.6 and installed 2.8.0 in my ['collect' space](https://collect.readwriterespond.com/) which is running your Indieweb-2016 theme with a basic child. It killed the posts:

![screenshot 2018-02-12 at 1 52 27 pm](https://user-images.githubusercontent.com/13294754/36082436-82db3462-0ffd-11e8-9ce7-68aa079591f1.png)

And removed some widgets and navigation options at the bottom of the screen:

![screenshot 2018-02-12 at 1 52 38 pm](https://user-images.githubusercontent.com/13294754/36082442-938697d4-0ffd-11e8-8d84-f80d021923ab.png)

I activated it in my main site running Independent Press and there were not consequences to speak of.

Apologies for not using the correct language. If there is anything you wish me to follow up with, let me know.

**Comment by dshanske** [comment]
So, problem but only with one theme?

**Comment by dshanske** [comment]
I need to test that and figure out why I guess.

**Comment by mrkrndvs** [comment]
It would seem that way. Maybe I install Independent Publisher on my Collect site and see what happens.

**Comment by dshanske** [comment]
I am using my 2016 fork on my test site.

**Comment by mrkrndvs** [comment]
Nope, stripped the widgets from Independent Publisher too. Not theme specific. Could there be a clash with another plugin? Also, the only post kind that seems to be broken is 'Photo'. The rest still seem to be working as expected.

Hope that helps.

**Comment by dshanske** [comment]
Odd, must have broken something trying to fix this.

**Comment by dshanske** [comment]
@mrkrndvs @raretrack I tried a different way of resolving this. It now will only automatically add photos if there is no src attributed tag in the post content.

**Comment by mrkrndvs** [comment]
Testing 3.0.0 and photo kind is working again thank you David. Also, no more doubling of the image too
![screenshot 2018-02-25 at 12 09 52 am](https://user-images.githubusercontent.com/13294754/36630798-60740ada-19c0-11e8-801e-a98221c8d96d.png)
