### ISSUE TITLE
Issue with Micropub & Post Kinds

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#151]
I'm getting this error in my micropub endpoint: https://xavierroy.com/?micropub=endpoint

I was getting this with 2.7.6... I then installed the 2.8.0 off Github.. Still getting this error. Any reasons why?

> Warning: Invalid argument supplied for foreach() in /home/xavroy1/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/class-kind-plugins.php on line 149
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home/xavroy1/xavierroy.com/wp-content/plugins/indieweb-post-kinds/includes/class-kind-plugins.php:149) in /home/xavroy1/xavierroy.com/wp-content/plugins/micropub/micropub.php on line 1092
> "missing access token"

**Comment by xavierroy** [comment]
Also getting these on the post page:

Warning: require_once(/home/xavroy1/xavierroy.com/wp-content/plugins/indieweb-post-kinds/templates/reply-metabox.php): failed to open stream: No such file or directory in /home/xavroy1/xavierroy.com/wp-includes/template.php on line 688

Fatal error: require_once(): Failed opening required '/home/xavroy1/xavierroy.com/wp-content/plugins/indieweb-post-kinds/templates/reply-metabox.php' (include_path='.:') in /home/xavroy1/xavierroy.com/wp-includes/template.php on line 688


I know it is still in dev.. just just letting you know :-)

**Comment by dshanske** [comment]
I'm about to release a new version, and we did a bunch of error checks in the last Micropub plugin release. Can you check on this?

**Comment by dshanske** [comment]
@xavierroy Is this still an issue?

**Comment by dshanske** [comment]
Closed due lack of updated report
