### ISSUE TITLE
Use og:description over meta description 

### ISSUE THREAD

**Issue by miklb** [dshanske/indieweb-post-kinds#160]
When parsing a GitHub repo, it is returning `meta` `description` which GitHub adds a generic description of their service, whereas `og:description` is the repo summary.

One could argue that's a bug on the GitHub side, but I thought I'd have a better chance of solving in the plugin.

In #wordpress you mentioned that `og;description` should take priority, just documenting the discussion.

**Comment by dshanske** [comment]
This should be addressed in the latest merge as well.
