### ISSUE TITLE
Media URLs

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#161]
Right now, the plugin doesn't support media URLs. It assumes media will be uploaded into the WordPress system. It doesn't try to sideload or otherwise.

**Comment by dshanske** [comment]
It probably should sideload and then harvest information from the attachment metadata. Should probably institute a warning  that a file will be sideloaded.

**Comment by dshanske** [comment]
I really need to do this to enhance photo, video, and audio posts.

**Comment by miklb** [comment]
I think that's what I attempted to tackle with #93 because I noticed there was two different ways OwnYourGram could pass a photo so I was trying to cover both cases. Or am I conflating two different things?

**Comment by dshanske** [comment]
I've been playing with the idea of having URLs that reflect media types download the file temporarily, look at the ID3 or EXIF tags, and try to generate a preview. The problem being that works pretty easily with an image file, but an audio or video file can be pretty large. So, in the latest master branch, I added code that will only try to do this if the file has a WordPress attachment ID, which means it would be local. 

I think the solution for now is to add a button for the WordPress upload popup, but looking for ideas.

Now, for things being passed by Micropub...Micropub already sideloads them if they are sent in as media.

**Comment by dshanske** [comment]
I have partially reverted this in the last update due some issues. A better version will return

**Comment by dshanske** [comment]
Addressed in latest master with using the media upload functionality in WordPress
