### ISSUE TITLE
Rich Embeds Disable Proper Markup

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#164]
It looks like the rich embeds might interfering with proper markup. With a rich embed, probably should have a hidden link marking things up.

**Comment by miklb** [comment]
As discussed in Slack, I have a solution that with a check to compare the embed url with the url sent could be sent as a PR https://github.com/miklb/independence/blob/master/kind_views/kind-reply.php#L24

**Comment by dshanske** [comment]
Added a hidden link inside the embed to address this problem a simpler way.
