### ISSUE TITLE
Alternative URL to /kind/

### ISSUE THREAD

**Issue by scottmallinson** [dshanske/indieweb-post-kinds#165]
Is it possible to change the post kinds URL to something other than /**kind**/note, e.g. /**blog**/note?

**Comment by dshanske** [comment]
Technically, 

https://developer.wordpress.org/reference/functions/register_taxonomy/

I suppose I could add a filter to allow it.

**Comment by scottmallinson** [comment]
Thanks for the pointer @dshanske. I'll do that 👍
