### ISSUE TITLE
read-status displaying "Array"

### ISSUE THREAD

**Issue by gRegorLove** [dshanske/indieweb-post-kinds#180]
It appears when the view file is displaying the `read-status` property from the mf2, it's not processing the resulting array first. It's output as a string at [this line](https://github.com/dshanske/indieweb-post-kinds/blob/master/views/kind-read.php#L27) so the variable is converted to a string and displays "Array".

Line 15 in that file is requesting the `read-of` property. I think updating that to `read-status` and making sure it is a string value before outputting it should resolve this.

Examples:
https://jackjamieson.net/433-2/
https://tiny.n9n.us/2018/06/19/4700/

@jackjamieson2 brought my attention to this via https://github.com/gRegorLove/indiebookclub/issues/8

**Comment by dshanske** [comment]
I saw and intend to fix when I get home
