### ISSUE TITLE
Use excerpt of Note Kind in All Posts title field

### ISSUE THREAD

**Issue by asuh** [dshanske/indieweb-post-kinds#181]
Considering that Notes allow the title field to be optional in the edit page, many or most notes that are published will have no title. In the All Posts view, that means you have a view that looks like this:

<img width="503" alt="no-title" src="https://user-images.githubusercontent.com/454064/41678869-2d64c0b4-7481-11e8-8d2e-903d9b17e9b2.png">

It would be helpful for all of those `(no title)` fields to show something useful considering the body of the post contains text. 

When no title is published, I propose that this field contain an excerpt of the content with a maximum of 280 characters in the spirit of a Tweet.

**Comment by dshanske** [comment]
Implemented. When there is no title, it will still show (no title) but it will also show the first 40 characters of the excerpt. May tweak it further later, but it seems to give you a sense of what this is about.

**Comment by asuh** [comment]
Looks good for now!
