### ISSUE TITLE
Post Editor problems with indiebookclub posts

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/indieweb-post-kinds#183]
@dshanske, Thanks again for such quick work resolving #180!

I'm having another minor problem:  When I try to edit a post created using indiebookclub, the post-editor fails to load completely.

The response properties field loads (see screenshot), but the post editor screen is otherwise blank. When I click 'screen options' or 'help' nothing happens. 

![screen shot 2018-06-20 at 3 44 41 pm](https://user-images.githubusercontent.com/12275399/41680905-f9db4f18-74a0-11e8-8558-b1847bdb7349.png)

I can resolve this problem by clicking 'clear' on the response properties box and then reloading — this makes the rest of the post editor load successfully. Therefore, I think the response properties are being populated incorrectly (and probably should not be populated at all for a read post, right?).

This seems to be consistent with all posts I make using indiebookclub.

**Comment by dshanske** [comment]
The post editor doesn't currently support the indiebookclub formatting. I will be looking to address in future.

**Comment by dshanske** [comment]
Put in a temporary fix. Want to release it and will work on something that better addresses the issue of different data formats later.
