### ISSUE TITLE
Error Activating Plugin

### ISSUE THREAD

**Issue by RossGoodman** [dshanske/indieweb-post-kinds#19]
I get the following error when I try and activate this plugin:

Fatal error: Cannot redeclare kindstyle_load() (previously declared in /var/sites/r/rossgoodman.com/public_html/wp-content/plugins/indieweb-taxonomy-master/indieweb-taxonomy.php:31) in /var/sites/r/rossgoodman.com/public_html/wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php on line 73

**Comment by dshanske** [comment]
Indieweb Post Kinds replaces Indieweb Taxonomy. They are the same plugin. The Taxonomy name was too vague. 

Please disable Taxonomy.

**Comment by RossGoodman** [comment]
Worked a treat.

Thanks

Ross

On 5 March 2015 at 16:24, David Shanske <notifications@github.com> wrote:

> Indieweb Post Kinds replaces Indieweb Taxonomy. They are the same plugin.
> The Taxonomy name was too vague.
>
> Please disable Taxonomy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dshanske/indieweb-post-kinds/issues/19#issuecomment-77395459>
> .
>



-- 
Ross

**Comment by nchenga** [comment]
i get the same error but didn't have indieweb taxonomy installed previously

**Comment by dshanske** [comment]
nchenga, can I have the exact error? Cut and paste?
