### ISSUE TITLE
array_key_exists() error in class-parse-mf2.php

### ISSUE THREAD

**Issue by khurtwilliams** [dshanske/indieweb-post-kinds#194]
This occasionally happens when I use a post kind that requires a URL. I am using the native WordPress editor.

[Wed Jul 18 07:03:34.179394 2018] [:error] [pid 17074] [client 69.142.91.253:45190] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-parse-mf2.php on line 249, referer: https://islandinthenet.com/wp-admin/post-new.php
[Wed Jul 18 07:03:34.179463 2018] [:error] [pid 17074] [client 69.142.91.253:45190] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-parse-mf2.php on line 249, referer: https://islandinthenet.com/wp-admin/post-new.php
[Wed Jul 18 07:03:34.179477 2018] [:error] [pid 17074] [client 69.142.91.253:45190] PHP Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-parse-mf2.php on line 871, referer: https://islandinthenet.com/wp-admin/post-new.php

(Originally published at: Island In The Net)

**Comment by dshanske** [comment]
No longer part of this repo. If not fixed, please refile in the https://github.com/dshanske/parse-this plugin if still an issue.
