### ISSUE TITLE
dshanske/indieweb-post-kinds – PHP Notices

### ISSUE THREAD

**Issue by dougbeal** [dshanske/indieweb-post-kinds#196]
`
PHP Notice: Only variables should be passed by reference in /var/www/html/wp-content/plugins/indieweb-post-kinds/views/kind-video.php on line 10
PHP Notice: Undefined index: kind in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php on line 32
PHP Notice: Undefined index: name in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 326
PHP Notice: Undefined index: name in /var/www/html/wp-content/plugins/indieweb-post-kinds/views/kind-checkin.php on line 14
PHP Notice: Undefined variable: action in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-mf2-debugger.php on line 90
`
href=’https://github.com/dshanske/indieweb-post-kinds/issues’&gt;

(Originally published at: https://crw.moe/b/ZQ)

**Comment by philbowell** [comment]
I also received this an error this morning:

```
wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 326
```

**Comment by dougbeal** [comment]
Noticies in last 10,000 message

1 PHP Notice: Undefined index: kind in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php on line 43
1754 PHP Notice: Undefined index: name in /var/www/html/wp-content/plugins/indieweb-post-kinds/views/kind-checkin.php on line 12
21 PHP Notice: Undefined index: type in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-plugins.php on line 117
21 PHP Notice: Undefined index: type in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/functions.php on line 11
166 PHP Notice: Undefined index: url in /var/www/html/wp-content/plugins/indieweb-post-kinds/views/kind-rsvp.php on line 11

**Comment by tw2113** [comment]
`PHP Notice: Only variables should be passed by reference in /indieweb-post-kinds/views/kind-video.php on line 10` fixed in dc5e97eb5e3e08ef47ee44383f84b1deac1cf20f

`PHP Notice: Undefined index: kind in /indieweb-post-kinds/includes/class-kind-metabox.php on line 32` is kind of lost since as the line numbers don't line up any more. Line 32 is now the start of a PHPDoc block.

`PHP Notice: Undefined index: name in /indieweb-post-kinds/includes/class-kind-view.php on line 326` has an array_key_exists check that fills in the index and then tries after with that newly set index.

`PHP Notice: Undefined index: name in /indieweb-post-kinds/views/kind-checkin.php on line 14`  This one probably needs an ifset() for `$name  = $mf2_post->get_single( $cite['name'] );`

**Comment by pauho** [comment]
Similar errors on 3.4.4 and 3.4.3, downgrading to 3.3.6 seems to have fixed it.

Warning: Illegal string offset 'author' in /public_html/wp-content/plugins/indieweb-post-kinds/views/kind-read.php on line 10

Fatal error: Uncaught Error: Only variables can be passed by reference in /public_html/wp-content/plugins/indieweb-post-kinds/views/kind-read.php:10 Stack trace: #0 /public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php(113): include() #1 /public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php(133): Kind_View::get_view_part('kind', 'read') #2 /public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php(179): Kind_View::get_display() #3 /public_html/wp-includes/class-wp-hook.php(287): Kind_View::content_response('<div class='e-c...') #4 /public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters('<div class='e-c...', Array) #5 /public_html/wp-includes/post-template.php(253): apply_filters('the_content', '') #6 /public_html/wp-content/themes/independent-publisher/content-single.php(53): the_content() #7 /public_html/ in /public_html/wp-content/plugins/indieweb-post-kinds/views/kind-read.php on line 10

**Comment by dshanske** [comment]
Darn...I thought I knocked all these down. I need to stop and fix this once and for all

**Comment by dshanske** [comment]
This shouldn't occur anymore.
