### ISSUE TITLE
Notice: Undefined index: name

### ISSUE THREAD

**Issue by metbril** [dshanske/indieweb-post-kinds#202]
> Notice: Undefined index: name in /home/deb38267n2/domains/robertvanbregt.nl/public_html/wp/wp-content/plugins/indieweb-post-kinds.BAK/includes/class-kind-view.php on line 321

https://github.com/dshanske/indieweb-post-kinds/blob/c460c4645cc3a60963aef0a1ba91a43ade0c4995/includes/class-kind-view.php#L321

I created 2 bookmarks:

- [1](
http://fogknife.com/2018-05-04-i-believe-in-the-indieweb-it-needs-to-believe-in-itself.html)
- [2](https://sebastiangreger.net/2018/05/indieweb-privacy-challenge-webmentions-backfeeds-gdpr/)

The first one shows ok, the second shows the error.

My guess it's to do with the author["name"].

**Comment by dshanske** [comment]
I thought I had checked every single index. Will fix this in next release

**Comment by philbowell** [comment]
I'm also receiving this error but on line 326.

```
Notice: Undefined index: name in /home/pbblog/public_html/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 326
```

Only seems to be on [this like](https://philbowell.blog/2018/23-07-2018-0753/) as an [earlier one](https://philbowell.blog/2018/20-07-2018-2011/) doesn't have it.

**Comment by dshanske** [comment]
Added some temporary code to address this. It isn't ideal, but want to eliminate the error before rewriting it.

**Comment by dshanske** [comment]
Closing this. Please reopen if version 3.1.0 doesn't address.
