### ISSUE TITLE
Stray empty twitter/publish url on h-feed

### ISSUE THREAD

**Issue by miklb** [dshanske/indieweb-post-kinds#209]
parsing my h-feed using mf2 plugin and default 2016 theme, the `h-feed` is picking up `https://www.brid.gy/publish/twitter` as a url. I suspect need to add a check to only insert that on single posts?

**Comment by dshanske** [comment]
This is a Bridgy Publish issue

**Comment by miklb** [comment]
my apologies I swore that repo was what I saw in my url bar.
