### ISSUE TITLE
OwnYourGram errors

### ISSUE THREAD

**Issue by stephenpieper** [dshanske/indieweb-post-kinds#223]
I’m testing the latest master version and the following error is occuring for any photo imported from OwnYourGram. The photos don’t get shown.
Notice: Object of class WP_Post could not be converted to int in …/wp-includes/functions.php on line 3808

**Comment by dshanske** [comment]
Great, will get on this.

**Comment by dshanske** [comment]
Is that the only line of errors? I'm trying to track what called that function.

**Comment by stephenpieper** [comment]
I checked the debug log and this error is also apearing there:

PHP Warning:  array_merge(): Argument #2 is not an array in .../wp-content/plugins/indieweb-post-kinds-master/includes/class-kind-view.php on line 129

**Comment by dshanske** [comment]
That is certainly an error checking bug, but it doesn't explain the issue. I'm thinking that the issue is the image is there, but isn't displaying. I did change how the code displays it to try and fix double display issues.

**Comment by dshanske** [comment]
If that is so, pushing a change should address the issue.

**Comment by dshanske** [comment]
@stephenpieper Try it now.

**Comment by stephenpieper** [comment]
I'm getting a whole bunch of errors now. It's only for that type of post (imported OwnYourGram photos). Everything else is fine.

**Comment by dshanske** [comment]
Can you post them?

**Comment by stephenpieper** [comment]
Here they are:

Warning: parse_url() expects parameter 1 to be string, array given in ...wp-includes/media.php on line 3918

Warning: strpos() expects parameter 1 to be string, array given in ...l/wp-includes/media.php on line 3925

Warning: preg_match() expects parameter 2 to be string, array given in ...wp-admin/includes/media.php on line 868

Notice: Object of class WP_Error could not be converted to int in .../wp-includes/post.php on line 5239

Warning: parse_url() expects parameter 1 to be string, array given in ...wp-includes/media.php on line 3918

Warning: strpos() expects parameter 1 to be string, array given in .../wp-includes/media.php on line 3925

Notice: wpdb::prepare was called incorrectly. Unsupported value type (array). Please see Debugging in WordPress for more information. (This message was added in version 4.8.2.) in .../wp-includes/functions.php on line 4161

Notice: wpdb::prepare was called incorrectly. The query only expected one placeholder, but an array of multiple placeholders was sent. Please see Debugging in WordPress for more information. (This message was added in version 4.9.0.) in .../wp-includes/functions.php on line 4161

Notice: Array to string conversion in ...wp-content/plugins/indieweb-post-kinds-master/parse-this/class-mf2-post.php on line 523

Notice: Array to string conversion in .../wp-content/plugins/indieweb-post-kinds-master/parse-this/class-mf2-post.php on line 523

Notice: Array to string conversion in .../wp-content/plugins/indieweb-post-kinds-master/parse-this/class-mf2-post.php on line 523

**Comment by dshanske** [comment]
Well, back to the drawing board

**Comment by dshanske** [comment]
I added some additional checks on this if you want to update. I think I found a few errors.

**Comment by stephenpieper** [comment]
Sorry for the delayed reply. The errors are still there after the latest updates. I'm using the Sempress theme so I'm wondering if anyone else can replicate this.

**Comment by dshanske** [comment]
I keep trying to solve the problem of duplicate photos and have ended up here

**Comment by dshanske** [comment]
Did the errors appear exactly the same as above?

**Comment by stephenpieper** [comment]
Yes. Just the same.

**Comment by dshanske** [comment]
Can you do me a favor? Install a plugin called post meta inspector, which should show you the metadata attached to the post, and paste it here?

**Comment by stephenpieper** [comment]
This is from one the posts showing errors:

Key.                Value
micropub_auth_response 'a:8:{s:10:"token_type";s:6:"Bearer";s:5:"scope";s:6:"create";s:2:"me";s:26:"https://stephenpieper.net/";s:9:"issued_by";s:53:"https://stephenpieper.net/wp-json/indieauth/1.0/token";s:9:"client_id";s:24:"https://ownyourgram.com/";s:9:"issued_at";i:1536009777;s:4:"user";i:2;s:13:"last_accessed";i:1536023424;}'

mf2_type 'a:1:{i:0;s:7:"h-entry";}'

mf2_content 'a:1:{i:0;s:50:"Garcia Peoples - Cash Crisis #vinyl #onmyturntable";}'

mf2_category 'a:3:{i:0;s:5:"vinyl";i:1;s:13:"onmyturntable";i:2;s:9:"instagram";}'

mf2_published 'a:1:{i:0;s:25:"2018-09-03T17:04:57+00:00";}'

mf2_syndication 'a:1:{i:0;s:40:"https://www.instagram.com/p/BnRY3F0lA29/";}'

mf2_photo 'a:2:{s:4:"type";a:1:{i:0;s:6:"h-cite";}s:10:"properties";a:1:{s:3:"url";a:1:{i:0;s:167:"https://scontent-sjc3-1.cdninstagram.com/vp/4e1c53b0601b663a4b28f91a337c7a66/5C19B9B1/t51.2885-15/fr/e15/s1080x1080/39604606_2064934336852984_7799574108894658560_n.jpg";}}}'

_edit_lock '1537957702:2'

_edit_last '2'

mf2_mp-syndicate-to 'a:1:{i:0;s:4:"none";}'

_bridgy_backlink 'true'

geo_weather 'a:2:{s:5:"units";s:1:"C";s:4:"icon";s:4:"none";}'

geo_public '1'

_jetpack_related_posts_cache 'a:1:{s:32:"8f6677c9d6b0f903e98ad32ec61f8deb";a:2:{s:7:"expires";i:1536540382;s:7:"payload";a:3:{i:0;a:1:{s:2:"id";i:2910;}i:1;a:1:{s:2:"id";i:2574;}i:2;a:1:{s:2:"id";i:3347;}}}}'

**Comment by dshanske** [comment]
That is exactly what I needed to know. This doesn't match up with the notation on how OYG loads photos, so I didn't account for it.

**Comment by stephenpieper** [comment]
I tested it today with a new photo and it was imported correctly. Thanks.
