### ISSUE TITLE
Posts listing page - Replace Notes title anchor (no title) with excerpt

### ISSUE THREAD

**Issue by asuh** [dshanske/indieweb-post-kinds#227]
I expect this isn't trivial b/c there are multiple parts to the anchor such as the aria attribute in addition to the title text.

The filter for `the_title` function is a great improvement for the Posts listing page so that we can see a ~40 character excerpt in addition to "(no title)". I'd love to see the below line updated to actually replace the **(no title)** text with the excerpt.

So instead of this:

> **This is a long note so it gets cut o..[(no title)](#)**
> This is a long note so it gets cut o..

it would instead just be this:

> [**This is a long note so it gets cut o..**](#)

This is the line where the above happens
https://github.com/dshanske/indieweb-post-kinds/blob/0d9bf44ff70d6da513b12b9abfb15ef79ffbd059/includes/class-kind-taxonomy.php#L68

**Comment by asuh** [comment]
Ok fair enough, but it's odd that the excerpt is showing twice? Maybe it can just show below **(no title)**?

**Comment by dshanske** [comment]
Regrettably, not easily.

**Comment by asuh** [comment]
Nice update for this one, I think what we have a good iteration with the diamond. That said, I see that all Kinds excerpts end with diamonds. Was the diamond intended to be displayed on all Kinds and `(no title)` posts?

**Comment by dshanske** [comment]
Correct. To indicate it has no title.
