### ISSUE TITLE
⚠ Version 3.1.1

### ISSUE THREAD

**Issue by mrkrndvs** [dshanske/indieweb-post-kinds#230]
I have found a few quirks with the new release. One thing is that when I try and publish a ‘Like’ using URL Forwarder it populates the title but does not include the link.

I will continue testing and try to make note of any consistencies.

(Originally published at: https://collect.readwriterespond.com/post-kinds-3-1-1/)

**Comment by dshanske** [comment]
@mrkrndvs Going to need more details on that to track it. I assume you are using URL Forwarder to go to the post editor with the ?kind=like&kindurl=URL option?

As for the other quirks, document them and I will continue to release minor fixes for any bugs discovered.

**Comment by mrkrndvs** [comment]
I have not been able to reproduce the issues I am having with my bookmarklets. Not sure if @chrisaldrich  has had any issues with his bookmarklets, as I [copied his code](https://boffosocko.com/2017/08/11/post-kinds-plugin-for-wordpress/#Bookmarklet+Configuration).

One thing I have noticed consistently is that Wordpress.com sites are not parsing any information when I add a link to the Response Properties box. When I run these using the Parse This tool I get an error:

`HTTP ERROR 500`

This is different to the cURL error occurring with other sites, such as [http://edte.ch/blog/](http://edte.ch/blog/) and [http://blog.williamferriter.com/](http://blog.williamferriter.com/).

`{"code":"http_request_failed","message":"cURL error 28: Connection timed out after 10001 milliseconds","data":null}`

I have simply been cutting and pasting.

**Comment by dshanske** [comment]
Any examples of the specific sites you tried? I will start investigating.

**Comment by mrkrndvs** [comment]
I just went through my last month of posts and here are some WordPress.com
sites that failed to parse:

-
https://biancahewes.wordpress.com/2018/10/25/texts-and-human-experiences-its-a-little-dry/
- https://nielsenportfolio.wordpress.com/2018/10/23/on-reading/
- https://theeduflaneuse.com/2018/10/21/redefining-school-leadership/
- https://dculberh.wordpress.com/2018/10/22/experimentation-matters/
- https://cpdin140.wordpress.com/2018/10/18/visualising-what-i-do-again
-
https://stupidqubit.wordpress.com/2018/09/25/stupid-qubit-001-what-the-photonic-muck-is-a-quantum-computer/

However in reviewing, I did happen to find some that did parse:

-
https://timespaceeducation.wordpress.com/2018/10/21/set-up-its-more-important-than-you-think/
- https://jennymackness.wordpress.com/2018/10/19/talking-about-dying/
- https://leadershipfreak.blog/2018/10/15/why-not-liking-is-easy/

I did not notice that first time around. Not sure if that helps David?

**Comment by mrkrndvs** [comment]
David, I just came across an interesting parsing error. When I add:

https://criticaltheoryoftech.com/2018/11/02/logic-and-rhetoric-the-problem-with-digital-literacy/

I get the usual error.

However, it works fine with the addition of AMP

https://criticaltheoryoftech.com/2018/11/02/logic-and-rhetoric-the-problem-with-digital-literacy/amp/

Maybe this is the cause of the WordPress.com issues?

**Comment by mrkrndvs** [comment]
@dshanske I also discovered that if you use the AMP link that it does not send through any webmentions if the author has set them up.

**Comment by dshanske** [comment]
@mrkrndvs Can you revisit this issue?

**Comment by mrkrndvs** [comment]
@dshanske I have retested the scenarios listed above, as well as a number of fresh links. I am no longer having the same issues.
