### ISSUE TITLE
Issue parsing URLs

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#234]
I tried to parse this url: https://www.imdb.com/title/tt8227226/

I'm getting the following error when using Post Kinds through a bookmarklet.
  Notice: Undefined index: scheme in /home/xavroy1/xavierroy.com/wp-includes/class-http.php on line 904
  Notice: Undefined index: host in /home/xavroy1/xavierroy.com/wp-includes/class-http.php on line 912
 this repeats multiple times...

If I try adding the url to the  URL field in Response Properties, I get no errors but nothing is displayed. 

When I used the Parse This page, I get the following:

> 
> <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/xavroy1/xavierroy.com/wp-includes/class-http.php:904) in <b>/home/xavroy1/xavierroy.com/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
> {"url":"http:\/\/www.imdb.com\/title\/tt8227226\/","name":"\"Riverdale\" Chapter Thirty-Six: Labor Day (TV Episode 2018)","summary":"Directed by Kevin Rodney Sullivan.  With K.J. Apa, Lili Reinhart, Camila Mendes, Cole Sprouse. As the jury begins deliberations in his murder trial, Archie makes a surprising request; Jughead leads the Serpents against the Ghoulies latest attack.","photo":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMzE4NDU3NTM5Nl5BMl5BanBnXkFtZTgwMzM2NjA1NjM@._V1_UY1200_CR585,0,630,1200_AL_.jpg","publication":"IMDb","type":"cite","_raw":{"jsonld":{"@context":"http:\/\/schema.org","@type":"TVEpisode","url":"\/title\/tt8227226\/","name":"Chapter Thirty-Six: Labor Day","image":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMzE4NDU3NTM5Nl5BMl5BanBnXkFtZTgwMzM2NjA1NjM@._V1_.jpg","genre":["Crime","Drama","Mystery","Romance"],"contentRating":"TV-14","actor":[{"@type":"Person","url":"\/name\/nm6216001\/","name":"K.J. Apa"},{"@type":"Person","url":"\/name\/nm3929887\/","name":"Lili Reinhart"},{"@type":"Person","url":"\/name\/nm6161516\/","name":"Camila Mendes"},{"@type":"Person","url":"\/name\/nm0819850\/","name":"Cole Sprouse"}],"director":{"@type":"Person","url":"\/name\/nm0838198\/","name":"Kevin Rodney Sullivan"},"creator":[{"@type":"Person","url":"\/name\/nm2630745\/","name":"Roberto Aguirre-Sacasa"},{"@type":"Person","url":"\/name\/nm2630745\/","name":"Roberto Aguirre-Sacasa"},{"@type":"Person","url":"\/name\/nm4983843\/","name":"Janine Salinas Schoenberg"},{"@type":"Person","url":"\/name\/nm4883879\/","name":"Arabella Anderson"},{"@type":"Person","url":"\/name\/nm2838820\/","name":"Britta Lundin"},{"@type":"Person","url":"\/name\/nm6295676\/","name":"Brian E. Paterson"},{"@type":"Person","url":"\/name\/nm3972627\/","name":"Tessa Williams"},{"@type":"Organization","url":"\/company\/co0284701\/"},{"@type":"Organization","url":"\/company\/co0330789\/"},{"@type":"Organization","url":"\/company\/co0274041\/"},{"@type":"Organization","url":"\/company\/co0005035\/"}],"description":"Chapter Thirty-Six: Labor Day is an episode of Riverdale starring K.J. Apa, Lili Reinhart, and Camila Mendes. As the jury begins deliberations in his murder trial, Archie makes a surprising request; Jughead leads the Serpents...","datePublished":"2018-10-10","keywords":"trial,labor day,swimming hole,father daughter relationship,tattoo","aggregateRating":{"@type":"AggregateRating","ratingCount":648,"bestRating":"10.0","worstRating":"1.0","ratingValue":"8.4"},"review":{"@type":"Review","itemReviewed":{"@type":"CreativeWork","url":"\/title\/tt8227226\/"},"author":{"@type":"Person","name":"rrrrr-92813"},"dateCreated":"2018-10-11","inLanguage":"English","name":"The worst episode ever","reviewBody":"The episode was so bad, that I've singned up for the website just to write this review. There were to much plot lines that could be enough for the whole season. Also the lines were so bad so the acting was terrible. I hope that the rest of the season won't be like it.","reviewRating":{"@type":"Rating","worstRating":"1","bestRating":"10","ratingValue":"1"}}},"meta":{"apple-itunes-app":"app-id=342792525, app-argument=imdb:\/\/\/title\/tt8227226?src=mdot","og":{"url":"http:\/\/www.imdb.com\/title\/tt8227226\/","image":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMzE4NDU3NTM5Nl5BMl5BanBnXkFtZTgwMzM2NjA1NjM@._V1_UY1200_CR585,0,630,1200_AL_.jpg","type":"video.episode","title":"\"Riverdale\" Chapter Thirty-Six: Labor Day (TV Episode 2018)","site_name":"IMDb","description":"Directed by Kevin Rodney Sullivan.  With K.J. Apa, Lili Reinhart, Camila Mendes, Cole Sprouse. As the jury begins deliberations in his murder trial, Archie makes a surprising request; Jughead leads the Serpents against the Ghoulies latest attack."},"theme-color":"#000000","pageId":"tt8227226","pageType":"title","subpageType":"main","fb":{"app_id":"115109575169727"},"title":"\"Riverdale\" Chapter Thirty-Six: Labor Day (TV Episode 2018) - IMDb","description":"Directed by Kevin Rodney Sullivan.  With K.J. Apa, Lili Reinhart, Camila Mendes, Cole Sprouse. As the jury begins deliberations in his murder trial, Archie makes a surprising request; Jughead leads the Serpents against the Ghoulies latest attack.","keywords":"Reviews, Showtimes, DVDs, Photos, Message Boards, User Ratings, Synopsis, Trailers, Credits","request_id":"DQ4SNNBM4E5EJBRDXFFG"},"images":{"0":"https:\/\/sb.scorecardresearch.com\/p?c1=2&c2=6034961&c3=&c4=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt8227226%2F&c5=c6=&15=&cj=1","1":"https:\/\/m.media-amazon.com\/images\/G\/01\/wprs\/images\/navbar\/imdbpro_logo_nb._CB484021162_.png","2":"https:\/\/m.media-amazon.com\/images\/G\/01\/wprs\/images\/navbar\/imdbpro_navbar_menu_user._CB484021156_.png","3":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMzE4NDU3NTM5Nl5BMl5BanBnXkFtZTgwMzM2NjA1NjM@._V1_UY268_CR110,0,182,268_AL_.jpg","4":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMjEwODgwOTY4MF5BMl5BanBnXkFtZTgwMjUwNDc1NjM@._CR17,151,1008,755_UX614_UY460._SY230_SX307_AL_.jpg","5":"https:\/\/m.media-amazon.com\/images\/G\/01\/IMDb\/icon\/play-button._CB318667375_.png","6":"https:\/\/m.media-amazon.com\/images\/G\/01\/IMDb\/icon\/play-button-hover._CB318667374_.png","7":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/nopicture\/medium\/film-3385785534._CB483791896_.png","8":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/nopicture\/medium\/tv-3264496829._CB470041855_.png","12":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/widget\/amazon._CB339202444_.png","13":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/plugins\/imdb_46x22-2264473254._CB470047279_.png","14":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/plugins\/imdb_star_22x21-2889147855._CB483525256_.png","15":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/nopicture\/small\/unknown-1394846836._CB470041629_.png","21":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/nopicture\/32x44\/name-2138558783._CB470041625_.png","36":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMjIzMDcyMDcxOV5BMl5BanBnXkFtZTgwMTg1NDk2NTM@._V1_SX116_CR0,0,116,172_AL_.jpg","37":"https:\/\/m.media-amazon.com\/images\/G\/01\/IMDb\/icon\/external-button._CB304896345_.png","38":"https:\/\/m.media-amazon.com\/images\/G\/01\/IMDb\/icon\/external-button-hover._CB304896345_.png","39":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMjQzNDQzMDQxOF5BMl5BanBnXkFtZTgwNTA4MTQwNjM@._V1_SX116_CR0,0,116,172_AL_.jpg","42":"https:\/\/m.media-amazon.com\/images\/M\/MV5BZTI0MjllMGMtOGYxMi00MTczLWJiMzMtNTA2ZmYxMDE5NmRiXkEyXkFqcGdeQXVyNjkwNzEwMzU@._V1_SX116_CR0,0,116,172_AL_.jpg","45":"https:\/\/m.media-amazon.com\/images\/M\/MV5BNzE0YzhlOTEtOWRhNy00ZDA0LWIyNTQtNTBiODRhZTRjZmJmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX116_CR0,0,116,172_AL_.jpg","48":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMjExMjk5NjI2NV5BMl5BanBnXkFtZTgwNTU3MzU4NDM@._V1_SX116_CR0,0,116,172_AL_.jpg"},"embeds":[],"audios":[],"videos":[],"links":{"canonical":"https:\/\/www.imdb.com\/title\/tt8227226\/","alternate":"https:\/\/m.imdb.com\/title\/tt8227226\/","icon":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/favicon-2165806970._CB470047330_.ico","shortcut icon":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/desktop-favicon-2165806970._CB484110913_.ico","apple-touch-icon":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/mobile\/apple-touch-icon-web-152x152-1475823641._CB470042035_.png","search":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/images\/imdbsearch-3349468880._CB470047351_.xml","image_src":"https:\/\/m.media-amazon.com\/images\/M\/MV5BMzE4NDU3NTM5Nl5BMl5BanBnXkFtZTgwMzM2NjA1NjM@._V1_UY1200_CR585,0,630,1200_AL_.jpg","stylesheet":"https:\/\/m.media-amazon.com\/images\/G\/01\/imdb\/css\/wheel\/nojs-2827156349._CB470041026_.css"},"content":""}}

**Comment by dshanske** [comment]
I do not get the same error when I try this. I get the scheme error, which I will try to figure out. But it parses.

**Comment by dshanske** [comment]
Fixed in Parse This repo and will merge into Post Kinds.
