### ISSUE TITLE
OwnYourGram imports coming in as video kind

### ISSUE THREAD

**Issue by vishae** [dshanske/indieweb-post-kinds#237]
Recently I’ve noticed that OwnYourGram imports are coming in as video kind instead of photos kind. Not sure if this is an OwnYourGram or Post Kinds issue. 

Example: https://www.serenawho.com/2018/11/16/7654/

(Cross posted this issue in both OwnYourGram and Post Kinds)

**Comment by dshanske** [comment]
I fixed something on the Micropub side that should help this and OwnYourGram had a fix on their side as well.
