### ISSUE TITLE
Undefined function parse_hfeed()

### ISSUE THREAD

**Issue by boricensis** [dshanske/indieweb-post-kinds#238]
From my log, including stack trace:

[Sun Nov 18 03:27:17.939652 2018] [:error] [pid 972] [client 70.69.20.27:62869] PHP Fatal error: Uncaught Error: **Call to undefined function parse_hfeed()** in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this-mf2.php:712

Stack trace:
#0 /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this.php(140): Parse_This_MF2::parse(Array, 'https://theuntr...', false)

#1 /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this-api.php(97): Parse_This->parse()

#2 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(936): Parse_This_API::read(Object(WP_REST_Request))

#3 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))

#4 /var/www/html/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/parse-this/1.0...')

#5 /var/www/html/wp-includes/class-wp-hook.php(286): rest_api! _loaded(Object(WP))

#6 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)

#7 /var/www/html/wp-includes/plug in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this-mf2.php on line 712, referer: https://itheorist.com/wp-admin/post-new.php?kind=like 

Same error happened with referrer:  https://itheorist.com/wp-admin/post-new.php?kind=bookmark on line 712 of /var/www/html/wp-includes/plug in /var/www/html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this-mf2.php

**Comment by dshanske** [comment]
It is defined in the current version. It should resolve when I push the next update.
