### ISSUE TITLE
array_filter error when publishing

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#240]
I'm getting this error when publishing posts:
Warning: array_filter() expects parameter 1 to be array, boolean given in /.../.../indieweb-post-kinds/includes/class-kind-metabox.php on line 330
> $fetch = array_filter( $mf2_post->fetch( $type ) );

I'm not sure if causes the data to be displayed in the home page , but not in the post page: See https://xavierroy.com/2018/12/07/wolverine-the-long-night-ch-4-hunters/
The data is displayed in the home page, but on the individual post page.

**Comment by dshanske** [comment]
It should check if the information is there before trying to filter it. Will fix that, but it would still mean it has no info

**Comment by dshanske** [comment]
I see that the data isn't displayed, but it shouldn't change based on single or archive page due this.

**Comment by dshanske** [comment]
Should be resolved in latest dev version. Specifically the error.
