### ISSUE TITLE
missing SimplePie/Credit.php

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/indieweb-post-kinds#242]
I encountered this warning when using Yarns to parse a feed at https://www.microsoft.com/en-us/research/feed/

PHP Warning:  require_once(/.../wp-content/plugins/indieweb-post-kinds/includes/parse-this/vendor/simplepie/simplepie/library/SimplePie/Credit.php): failed to open stream: No such file or directory in /.../wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-parse-this.php on line 109

Since the copy of parse-this included in Yarns has this file, I think the issue is that the /vendor/simplepie folder seems to be missing in Post Kinds.

**Comment by dshanske** [comment]
Bundled this, and also rewrote Parse This to include this lower down in the chain of items loaded.
