### ISSUE TITLE
Rewrite rule for post kind feeds broken

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#243]
The feed rewrite rule for post kinds seems to be broken. https://xavierroy.com/kind/watch/feed and http://xavierroy.com/feed/?kind=watch are supposed to be the same feed, but the ..kind/watch/feed isn’t working as expected.

(Originally published at: https://wp.me/p63TI-1Iy)

**Comment by dshanske** [comment]
This is fixed in development.
