### ISSUE TITLE
Cannot create bookmark with empty content

### ISSUE THREAD

**Issue by metbril** [dshanske/indieweb-post-kinds#246]
If you manually create a bookmark through the admin panel, the page is not saved, and if you try to open it, it shows a 404.

1. Go to https://example.com/wp/wp-admin/post-new.php?kind=bookmark
2. type a URL, e.g.g. https://indieweb.org
3. Click the Name field and wait for the title being fetched. Close the popup
4. Save the post
5. Click the "view post" link

This will lead you to the 404-page.

If you type anything in the content field, even just a dot ('.'), the post will be saved in the database and you can view it.

**Comment by dshanske** [comment]
@metbril Cannot reproduce this. Please reopen if still an issue.
