### ISSUE TITLE
Cannot find the box with the post kinds

### ISSUE THREAD

**Issue by olebrussels** [dshanske/indieweb-post-kinds#247]
Hello David, 

I have a WordPress 5.0.3 running Independent Publisher theme. The post kinds plugin is activated . I just **can't see the meta box with the Post Kinds Plugin** for choosing what kind of post one is creating.
I am following the tutorial from [Chris Aldrich](https://boffosocko.com/2018/04/27/setting-up-wordpress-for-indieweb-use/) but the UI is older version of wordpress.

I am not sure what to do... Do you have a video maybe with an explanation or where can i find this box?

Thank you very much for your help.

**Comment by dshanske** [comment]
Are you using the new block editor or the classic editor?

**Comment by olebrussels** [comment]
awesome! it works. thank you David
