### ISSUE TITLE
Cannot activate plugin

### ISSUE THREAD

**Issue by dougmckown** [dshanske/indieweb-post-kinds#25]
Installed it; when trying to activate:

Fatal error: Cannot redeclare kindstyle_load() (previously declared in .../wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php:54) in .../wp-content/plugins/indieweb-post-kinds-master/indieweb-post-kinds.php on line 55

**Comment by dshanske** [comment]
Looks like you have the stable and the development version installed.
