### ISSUE TITLE
Post editor URL doesn't display editor

### ISSUE THREAD

**Issue by kimberlyhirsh** [dshanske/indieweb-post-kinds#250]
When I use Post Kind WordPress editor URLs with the ?kindurl= extension, I get an editor window that only has a title box and a response properties box but nothing else, and the response properties box only has the "response properties" title and no content. I first encountered this with Inoreader's custom URL feature but found it also occurred when inputting the editor URL directly into my browser's address bar. Here's an example URL I might give Inoreader, where [URL] is Inoreader's URL variable: https://example.com/wp-admin/post-new.php?kindurl=[URL]&kind=reply
If I do it with just kind=reply without trying to use kindurl=, it's a normal editor with reply selected as the post kind and a blank response properties box as you'd expect.

![image](https://user-images.githubusercontent.com/5825002/54695224-f344d080-4aff-11e9-8fb9-2d52019bf028.png)

**Comment by mrkrndvs** [comment]
I get the same situation on Android when I use the share function. I think
the reason is because sharing includes both the title and URL.

**Comment by dshanske** [comment]
Resolved in dev version. Will create a new release soon.
