### ISSUE TITLE
3.2.3 permalink quirks with new posts and draft posts

### ISSUE THREAD

**Issue by asuh** [dshanske/indieweb-post-kinds#255]
Update 3.2.3 creates a couple of permalinks problems.

**Scenario 1**
1. Create new post as Note, save text in the editor but leave title blank.
2. Save as Draft
3. Update and change permalink 
4. Save as Draft again
5. You'll see permalink doesn't change

Same with title and editor content

**Scenario 2**
1. Create new post as Note, add text to title and editor content, title becomes permalink
2. Save as Draft
3. Permalink is instead showing content instead of title

**Comment by dshanske** [comment]
Pushed an attempt to fix this to development.

**Comment by asuh** [comment]
As of 3.2.6, scenario 2 above appears to be fixed.

Scenario 1 still has quirks:

1. Create new post as Note, save text in the editor but leave title blank.
2. Save as Draft
3. Update and change permalink

At this point, I don't need to save the Draft because the permalink does not update itself to the text I entered. It keeps the saved permalink from the text entered in the editor from step 1.

**Comment by asuh** [comment]
Tested against 3.3.1 and Scenario 1 above still exists

**Comment by dshanske** [comment]
I did not address fixes to this in 3.3 due the need to release some other fixes. Will try again soon

**Comment by dshanske** [comment]
I fixed this one in the latest push.

**Comment by asuh** [comment]
I can confirm this isn't an issue anymore! Thanks, @dshanske!
