### ISSUE TITLE
Exclude Post Kinds from Front Page

### ISSUE THREAD

**Issue by xavierroy** [dshanske/indieweb-post-kinds#256]
Is there a possibility of excluding certain post kinds from the front page? It could be a radio button/checkbox for each kind in the Post Kinds option page. I use Eat/Drink post kinds and I do not want them to be displayed in the front page 😉

(Originally published at: https://xavierroy.com/b/2ff)

**Comment by stephenpieper** [comment]
If the Eat/Drink posts all have the same category and you don't mind using a Wordpress plugin then Ultimate Category Excluder will do this very well. I use it to keep certain types off the front page and out of RSS feeds.

**Comment by xavierroy** [comment]
I use the same logic to hide them. Posts from Teacup do not allow a category to be set. So they are displayed on the home page.

**Comment by dshanske** [comment]
Related #257

**Comment by dshanske** [comment]
Address in 3.6.0
