### ISSUE TITLE
Filter post kinds out from a feed

### ISSUE THREAD

**Issue by RosemaryOrchard** [dshanske/indieweb-post-kinds#257]
Currently I syndicate 2 categories to micro.blog via RSS, but I would like to be able to exclude certain post kinds (such as check ins) from these feeds. Is there a way to do so, or can we add one? :)

**Comment by dshanske** [comment]
Related #256

**Comment by dshanske** [comment]
This is now in master branch 

https://github.com/dshanske/indieweb-post-kinds/commit/6366d0af1e23046a50c9a30f512ed867d83a3a8e

**Comment by dshanske** [comment]
You can do this as follows

https://example.com/category/example/feed/?exclude_kind=note,checkin
https://example.com/exclude/kind/note,checkin/feed/
