### ISSUE TITLE
remove inline style of the post-kinds-icon

### ISSUE THREAD

**Issue by pfefferle** [dshanske/indieweb-post-kinds#262]
Can you remove the inline sizing of the post-kinds icon or provide a function where I can get only the svg icon without the span wrapper?

I use the following code: https://github.com/pfefferle/Autonomie/blob/master/integrations/post-kinds.php#L42 and it looks that nice. See an example here: https://mrkapowski.com/

**Comment by dshanske** [comment]
I will provide the function. I have an issue that maybe you could help with that I was trying to fix.

**Comment by dshanske** [comment]
https://indieweb.org/Fatwigoo

**Comment by dshanske** [comment]
I found out that micro.blog had to code special css to avoid giant icons in the feed

**Comment by pfefferle** [comment]
you can keep the `height`, but please remove the `margin` or at least use a specific `margin`, like for example `margin-right`.

**Comment by dshanske** [comment]
I am going to switch to right

**Comment by dshanske** [comment]
Pushing this out now.
