### ISSUE TITLE
the_excerpt output not fully filtered in Kind_View::excerpt_response

### ISSUE THREAD

**Issue by MrKapowski** [dshanske/indieweb-post-kinds#263]
I reported an issue with the Autonomie theme earlier, which after a short discussion looks to be an issue with Post Kinds: #https://github.com/pfefferle/Autonomie/issues/23.

As a quick summary:

* If Post Kinds is **disabled**, `the_excerpt()` applies various 'the_excerpt' filters to the post excerpt. This includes things like `wpautop` for automatic line breaks, etc.
* If Post Kinds is **enabled**, `the_excerpt()` does not apply these filters to the post excerpt, leading to behaviour inconsistent with expectations - no wrapping `<p>` tags, or any other customisations. I guess filters added with an earlier priority than Post Kinds might work - I haven't tested this yet - but the defaults seem to be assigned a later priority.

I'm not sure if I've explained this clearly, so I'll leave an example page online for now: https://mrkapowski.com/?s=test. To work around the issue I'm planning to use a child theme to remove the Post Kinds filter from the_excerpt, using `remove_filter( 'the_excerpt', array( 'Kind_View', 'excerpt_response' ), 20 );` - but I'll hold off until you've been able to take a look.

**Comment by dshanske** [comment]
You could also file an issue

**Comment by dshanske** [comment]
https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/class-kind-view.php#L139

**Comment by dshanske** [comment]
The question is why is this happening.

**Comment by dshanske** [comment]
My priority is 20. What you are looking for is at 10. Solution, change priority to 9
