### ISSUE TITLE
Fields don't seemingly change once a particular kind is selected

### ISSUE THREAD

**Issue by Cambridgeport90** [dshanske/indieweb-post-kinds#266]
Not sure whether or not I'm doing something wrong, but while using the latest versions of both Wordpress and Post Kinds, I can't for some reason figure out how to make the corresponding fields to show up; for instance, I tried a repost from The New Yorker earlier (look over at the latest note on [Katherine Moss's Blog](http://cambridgeport90.net), and you'll see what I'm talking about. Happens the same way with replies, as well. I could have the post format incorrect, so it could be me. let me know. Thanks.

**Comment by dshanske** [comment]
There should be a set of fields in the classic editor above the content box. If hidden, they can be selected in the screen options under response properties.

**Comment by Cambridgeport90** [comment]
Thanks for the hand! I didn’t see those at all. I never would have thought to look under there. I’m going to try and edit my last

**Comment by dshanske** [comment]
It's an issue I need to find a better solution to.

**Comment by Cambridgeport90** [comment]
I think that part of it is on Wordpress; since it’s not a built in functionality, or at least at the moment, it might be the only thing you can do.

**Comment by dshanske** [comment]
Well, if Gutenberg can make an alternate editor, maybe I need one for everything but articles.

**Comment by Cambridgeport90** [comment]
That could work, but then again, there are those who prefer the classic editor like myself, but that is more because of screen reader usage, to be honest.

**Comment by dshanske** [comment]
I always hope I did accessibility well enough, or at least someone will tell me so I can improve.

**Comment by Cambridgeport90** [comment]
They are labeled perfectly now that I checked the box under screen options. Thanks!
