### ISSUE TITLE
Response Properties URL validation event firing too often 

### ISSUE THREAD

**Issue by asuh** [dshanske/indieweb-post-kinds#271]
Not sure why I hadn't noticed before but after updating to version 3.2.6, any time I click inside of the URL field, I get the alert saying "Invalid URL". It might be good to have an additional check to make sure the URL value is populated before validation occurs. Otherwise, I get multiple alerts trying to focus on the field, go to get the URL and paste into the field.

**Comment by dshanske** [comment]
Fixed in next version.
