### ISSUE TITLE
Name audiofile twice in post

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/indieweb-post-kinds#272]
I used the audio post kind for the first time today ([link](https://diggingthedigital.com/in-hiding/)) and as you can see at this link it shows the name of the audio file twice. I also use it in the title, but that's my own choice. It shows the title behind the audio-icon and once above the player. What would be the best way to only show it once? I can perhaps hide one of the two with CSS but I think the one above the audio-player could be dismissed? 

It also doesn't show the name of the author even though I've included this in the Response Properties in the WP admin. Clearing cache doesn't help sofar. 

Any help is appreciated.

**Comment by dshanske** [comment]
I was advised of the problem and will be investigating

**Comment by dshanske** [comment]
I am working on moving storage of these properties to the media itself. It should fix the problem

**Comment by frankmeeuwsen** [comment]
OK, is there anything on my part I should do? Or will already published articles update itself?

**Comment by dshanske** [comment]
It is a display problem, not a data storage issue

**Comment by frankmeeuwsen** [comment]
OK. So if it's a display problem, I still have no idea where to go and how to fix this....
