### ISSUE TITLE
Photo Kind error

### ISSUE THREAD

**Issue by neoaboriginal** [dshanske/indieweb-post-kinds#273]
I have a visible error when using the photo-kind: Warning: DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 6 in /home/neoabori/public_html/wp-content/plugins/indieweb-post-kinds/includes/parse-this/includes/class-mf2-post.php on line 637 - is there a way to remove this? The problem does not appear when the photo is from ownyourgram. Also had the duplicate photos issue #147

**Comment by dshanske** [comment]
@neoaboriginal The figure issue I understand. There are options to fix it in the next version. In the meantime turn off WP_DEBUG. Re #147...had or have? Is it fixed?

**Comment by neoaboriginal** [comment]
Followed the instructions [here](https://docs.whmpress.com/faq/how-to-enable-or-disable-wp_debug-using-file-manager/), but no success.

#147 shows up regularly, but I end up deleting the attached picture, so I suppose the other one is from the instagram url. Not as big an issue as this one (#273)

**Comment by dshanske** [comment]
Will work on inhibiting the error. Will be happy to discuss the other issue as well
