### ISSUE TITLE
How to exclude kinds in RSS feed?

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/indieweb-post-kinds#275]
As referenced in #257 I try to see a feed from my own site with the following URL: https://diggingthedigital.com/exclude/kind/note/feed/ I would expect a feed without my note Post Kinds, but I get a 404. I am on version 3.2.6 of the plugin. I already tried to disable all plugins and only enable Post Kinds and Classic Editor, but this didn't solve the problem.
What can I do to make feeds like above possible?

**Comment by dshanske** [comment]
I will adjust as I see the default feed is acting up on mine. Even though it comes up. Go to the settings page, go to Permalinks and just save the page

**Comment by frankmeeuwsen** [comment]
Closing the issue reminded me I had to test your solution :-) Unfortunately I still get a 404 on the above URL after I saved the permalink structure again. Anything else I can try?
