### ISSUE TITLE
"-s next to media

### ISSUE THREAD

**Issue by neoaboriginal** [dshanske/indieweb-post-kinds#276]
Is there a way to remove these quote signs? I cannot figure out why they show up on some posts, and not on others. I'm looking for a consistent design on my website.

![image](https://user-images.githubusercontent.com/51783583/59565674-9b622b00-9056-11e9-95c8-3b6307223bf2.png)

**Comment by dshanske** [comment]
Your theme adds them for blockquotes

**Comment by dshanske** [comment]
As a style, not a plugin issue per se, closing this, as can be resolved in css
