### ISSUE TITLE
Add filter to allow another plugin to add views

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#277]
In case someone doesn't want to put it in a theme, they could override it with a filter. To solve a @xavierroy problem

**Comment by xavierroy** [comment]
If it is not theme-independent or Post-Kinds plugin location like say a views folder in "wp-uploads". That way people can switch themes and update plugins without losing customisations

**Comment by dshanske** [comment]
You can't have loadable PHP in the uploads directory. Security issue on some sites
