### ISSUE TITLE
Classic Editor warning text

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/indieweb-post-kinds#279]
If classic editor is not installed, this plugin displays a warning: 

>Classic Editor Plugin is not active. This plugin will not function correctly at this time without using the Classic Editor.

In my experience, this warning appears across the wordpress dashboard, and so it's not clear that "this plugin" refers to IndieWeb Post Kinds.

Suggest rephrasing to:
>Classic Editor Plugin is not active. **IndieWeb Post Kinds** will not function correctly at this time without using the Classic Editor.

or something to that effect

**Comment by dshanske** [comment]
Resolved
