### ISSUE TITLE
Allow to set a stream as "Your Latest Posts"

### ISSUE THREAD

**Issue by bekopharm** [dshanske/indieweb-post-kinds#288]
The plugin should allow streams like `/kind/reply/` to be set as "Your Lates Posts".

![image](https://user-images.githubusercontent.com/5016428/64083417-1ebf1e80-cd20-11e9-827b-1afcfbd29345.png)

This would allow for easier sorting to declutter the "Latest Posts" page.

Related: #102 #256

**Comment by dshanske** [comment]
As #102 and #256 are now addressed, this specific version of same will likely not.
