### ISSUE TITLE
Test for ClassicPress

### ISSUE THREAD

**Issue by PC-Rights** [dshanske/indieweb-post-kinds#292]
For ClassicPress installations, the Classic Editor is not necessary as ClassicPress does not use any Gutenberg code.

To test if ClassicPress is installed and disable the Classic Editor error message, please modify the indieweb-post-kinds.php file as below:

At around line 43, replace current code with:

`function is_classicpress() { 
     if ( function_exists( 'classicpress_version' ) ) {
          return true;
     } else {
	add_action( 'admin_notices', array( 'Post_Kinds_Plugin', 'classic_editor_error' ) );
     }
}`

**Comment by dshanske** [comment]
Will see about doing this in next release

**Comment by PC-Rights** [comment]
Thanks for reading and considering this. While ClassicPress is only just over a year old, I think the fact it is gutenberg-free will only see the fork grow.

**Comment by dshanske** [comment]
I am keeping version 4.9 compatibility in my plugins for as long as possible for that reason. I have backported some simple functions for older versions.

**Comment by dshanske** [comment]
Resolved via https://github.com/dshanske/indieweb-post-kinds/commit/d8c0e517c9c8c4a9e4af135632b2846925da2c81
