### ISSUE TITLE
"hentry" instead of "h-entry" in posts

### ISSUE THREAD

**Issue by kevquirk** [dshanske/indieweb-post-kinds#303]
Hi,

I've just been informed that a webmention I sent to someone isn't parsing on their site correctly. On further inspection, it appears to be an issue with my site.

If you look at the source for [this page](https://kevq.uk/reply-to-from-google-to-nextcloud-for-my-contacts-calendar/), line 88 says the following:

`<article id="post-1663" class="post-1663 post type-post status-publish format-standard hentry category-notes kind-reply">`

**Should `hentry` not be `h-entry`?**

I first thought it might have been my caching plugin (Rocket WP) minifying the HTML a little much, but after testing it without any caching, the class remains the same.

I've tried searching open issues, but can't find anything relating to this issue. Any suggestions, or is this a bug?

Thanks,

Kev

**Comment by dshanske** [comment]
It should, but that is added by WordPress core, not Post Kinds. hentry is classic microformats, h-entry is the newer microformats 2

**Comment by dshanske** [comment]
http://php.microformats.io/?url=https%3A%2F%2Fkevq.uk%2Freply-to-from-google-to-nextcloud-for-my-contacts-calendar%2F

This is how your page parses

**Comment by kevquirk** [comment]
Ah, that's interesting. I didn't know there was a micrformats parser. Apologies, I would have used that first had I known. Everything looks like it's got the correct classes to my eye.

Appreciate the quick response on this.

**Comment by dshanske** [comment]
Any time
