### ISSUE TITLE
Reply Context: Avatar issue

### ISSUE THREAD

**Issue by pfefferle** [dshanske/indieweb-post-kinds#308]
If I try to reply to: https://notiz.blog/2020/07/28/working-draft-revision-435/

I get:

```HTML
<img class="u-photo" src="[object Object]" alt="Matthias Pfefferle" width="32" height="32">
```

**Comment by dshanske** [comment]
Related #309 

I'm fixing it. It's the new PHP-MF2 with the alt text parsing for imgs.
