### ISSUE TITLE
Array to strong conversion error?

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/indieweb-post-kinds#309]
I changed theme from Indieweb publisher to Genesis with Genesis Sample. I try to keep it as simple as possible. I just liked a page with a post kind Like and now on the hompage it shows "Notice: Array to string conversion in /kunder/burokr_5601/diggin_7791/public/wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 467" It turns out this error is shown in the Author Photo URL field of the post. 

What's going on and what can be done to fix this error? I now deleted the text and it's gone on the frontend, but I have no idea when this might happen again?

<img width="820" alt="Schermafbeelding 2020-08-04 om 19 49 03" src="https://user-images.githubusercontent.com/1940855/89327280-fc4e2780-d68b-11ea-8f85-53b925656ba9.png">

**Comment by dshanske** [comment]
It means the author had multiple photos found. I need to rewrite the logic on that again.

**Comment by dshanske** [comment]
I found the problem. The newest php-mf2 turns photo into an associative array if there is alt text. I need to update to account for that.
