### ISSUE TITLE
Class Kind-Post-Widget throws Fatal Error

### ISSUE THREAD

**Issue by bekopharm** [dshanske/indieweb-post-kinds#313]
Updated to post-kinds `3.4.2` this morning. Post Kind Widgets now crash:

```
PHP Fatal error:  Uncaught Error: Only variables can be passed by reference in ./wp-content/plugins/indieweb-post-kinds/includes/class-kind-post-widget.php:86
Stack trace:
#0 ./wp-content/plugins/indieweb-post-kinds/includes/class-kind-post-widget.php(66): Kind_Post_Widget->get_the_title()
#1 ./wp-content/plugins/indieweb-post-kinds/includes/class-kind-post-widget.php(51): Kind_Post_Widget->get_the_link()
#2 ./wp-includes/class-wp-widget.php(380): Kind_Post_Widget->widget()
#3 ./wp-includes/widgets.php(805): WP_Widget->display_callback()
```

This breaks site rendering including footer and login-overlay (so basically login functionality for average WordPress users).

**Comment by bekopharm** [comment]
Reverted back to `3.3.6` by unpacking https://downloads.wordpress.org/plugin/indieweb-post-kinds.3.3.6.zip manually into `wp-content/plugins/` (moved `3.4.2` before) and the problem is gone.

**Comment by dshanske** [comment]
I was away on religious observance all day. Give me a day or so and I should have this fixed. I run the widget and mine didn't crash in testing, but I'll run it down. The changes to the plugin at the low level were large. I thought I got them all.

**Comment by dshanske** [comment]
Should be resolved now.
