### ISSUE TITLE
URL deleted after second Save As Draft only if Name is empty

### ISSUE THREAD

**Issue by GidiKroon** [dshanske/indieweb-post-kinds#314]
I don't know what should be in the Name field, so I leave it empty after filling in a url in the URL field; all other response fields remain empty as well. When I Save as Draft, the content of the URL field is moved to one of the mf2 custom fields and the URL field itself is emptied. If I preview, it shows e.g. a repost-icon, but not the reposted post nor any link to it. If I then Save As Draft again, the mf2 custom field is itself deleted and the URL is lost.

If I do the same but manually fill in a Name with any value, the URL is not deleted when doing Save As Draft. In fact the mf2 custom field is not created at all. Previewing the post shows that it works and the reposted post is shown embedded.

This behaviour is on 3.4.3, and I think it was on 3.4.1 as well. I never tested on 3.4.0 or 3.4.2.

**Comment by dshanske** [comment]
Will work on it. Did a massive rewrite to the save/retrieve code and I thought I knocked all the bugs out before release. 3.4.1, 2, 3 are all minor bug fixes. Give me a day or two and I should get out a new version

**Comment by GidiKroon** [comment]
It works fine in 3.4.4, thanks!
