### ISSUE TITLE
Uncaught Exception: DateTime::__construct()

### ISSUE THREAD

**Issue by troutcolor** [dshanske/indieweb-post-kinds#316]
After posting a like, I got a email from WordPress, Your Site is Experiencing a Technical Issue. 

WordPress caught an error with one of your plugins, Post Kinds.

the mail contained some details:
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.5.1
Current theme: sempress Child (version 1.0.0)
Current plugin: Post Kinds (version 3.4.6)
PHP version 7.3.3

Error Details
=============
An error of type E_ERROR was caused in line 252 of the file /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/includes/time-functions.php. Error message: Uncaught Exception: DateTime::__construct(): Failed to parse time string (Invalid dateTInvalid date+01:00) at position 0 (I): The timezone could not be found in the database in /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/includes/time-functions.php:252
Stack trace:
#0 /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/includes/time-functions.php(252): DateTime->__construct('Invalid dateTIn...')
#1 /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php(224): divide_datetime('Invalid dateTIn...')
#2 /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/templates/reply-details.php(14): Kind_Metabox::kind_the_time('cite_published', 'Published/Relea...', 'Invalid dateTIn...', 'published')
#3 /Customer_web_sites/johnjohnston/public_html/blog/wp-content/plugins/indieweb-post-kinds/templates/reply-metabox.php(118): require_once('/Custom

I don't see any problem on the site, but though you might like to see this. The post in question is:
https://johnjohnston.info/blog/13548-2/

cheers
John

**Comment by dshanske** [comment]
I found several time related issues where I was not validating the input. I'm putting in extra checks and normalization functions to standardize the input. On the URL you were attempting to read, https://www.smashingmagazine.com/2020/08/autonomy-online-indieweb/. It gets the published time from the Open Graph meta tag article:published_time.

Now, according to the OGP spec, this should be in ISO8601 format, or `2020-08-27T11:00:00+00:00`
Smashing Magazine is using `2020-08-27 11:00:00 +0000 UTC`

I'm not quite sure what format that is supposed to be, but I'm guessing no one ever told them. So, going forward, Parse This will attempt to read and convert all time strings into ISO8601. It was already doing this in some places, I'm checking to add it to every place it could be needed.
