### ISSUE TITLE
Updated to post-kinds 3.4.8 - some meta data gone

### ISSUE THREAD

**Issue by bekopharm** [dshanske/indieweb-post-kinds#317]
I updated to ` 3.4.8` and many of the meta data is gone.

Here is an example of a Like:

![grafik](https://user-images.githubusercontent.com/5016428/95862296-01ea7c80-0d63-11eb-9d8b-e93ea93850e9.png)

Here is what it was (rolled back from snapshot to `3.4.4 `)

![grafik](https://user-images.githubusercontent.com/5016428/95862911-d61bc680-0d63-11eb-9b47-ffb1711b9206.png)

Can't identify a pattern. Some data survived.
I can provide you with a database dump.

**Comment by dshanske** [comment]
3.4.8 was designed to migrate old data from mf2_cite...so it would not lose any data.. just be misdisplaying

**Comment by dshanske** [comment]
I have pushed to the GitHub repo some code to normalize the responses to hopefully eliminate this issue going forward. It's all the different formats that are allowed

**Comment by dshanske** [comment]
Pushed the code. It fixes a variety of issues.

**Comment by bekopharm** [comment]
Yes, looks way better :+1: 

Now it says 'an author' tho even if there is data:

![image](https://user-images.githubusercontent.com/5016428/95962965-5e06dc80-0e07-11eb-801a-d16988103a69.png)

![image](https://user-images.githubusercontent.com/5016428/95963029-6e1ebc00-0e07-11eb-9a9f-5f5447470d20.png)

**Comment by bekopharm** [comment]
Fixed with post-kinds `3.4.11` :+1:
