### ISSUE TITLE
Shortcode to display multiple post kinds

### ISSUE THREAD

**Issue by kevinjtracy** [dshanske/indieweb-post-kinds#322]
So, there are a lot of different post kinds; which is great.  However, linking to each kind creates a lot of different links that I'd prefer to have grouped together on static pages (perhaps with short introductions to the content).  It'd be great if we could use shortcode to combine different post kinds on static pages and control basic properties, such as how many posts are displayed per page and how many characters are displayed per post.  

For example:
On a page titled "Food Blog," I would use shortcode such as...

`[post-kind="eat,drink" limit=10 display=300]`

This would ideally display the first 300 characters of the 10 most recent "eat" and "drink" kinds with a "next" button at the bottom to see the next 10 posts.

**Comment by dshanske** [comment]
I do this with a variety of custom rewrites. Like /kind/eat,drink would generate an archive with just these two. Haven't done anything with the posts per page or characters. 

I could see if I could do a shortcode as well, but the rewrite would allow you to create a custom archive template in your theme.

**Comment by dshanske** [comment]
I've just added /kind/food as a rewrite to eat and drink.

**Comment by dshanske** [comment]
@kevinjtracy Does /kind/food satisfy?

**Comment by kevinjtracy** [comment]
Yes! This will be great.  Thank you.
