### ISSUE TITLE
webmention_links filter does not seem to work

### ISSUE THREAD

**Issue by pfefferle** [dshanske/indieweb-post-kinds#326]
I ran several tests and it seems that the `webmention_links` filter does not return valid data and that's why the target site will not be pinged when using Post-Kinds:

https://github.com/dshanske/indieweb-post-kinds/blob/53a4df798c1ac842a01953f9c4fa6596cc91bdce/includes/class-kind-taxonomy.php#L1068

**Comment by dshanske** [comment]
I can fix this now that you highlighted the issue.

**Comment by dshanske** [comment]
Opted for https://github.com/dshanske/indieweb-post-kinds/commit/cb36406787ccaac36ac5cb65ec304b630982e4bd instead of #327
