### ISSUE TITLE
Make AMP Compatible.

### ISSUE THREAD

**Issue by milindmore22** [dshanske/indieweb-post-kinds#328]
The Post Kinds plugin uses a script to add a timestamp hash to URL ( http://example.com/#t=5)

I am not sure if the amp component for video and audio has support for it. also not sure if amp-script will help given that it runs in Worker DOM. I am still looking for a solution.

This is not a vital functionality and can be ignored, we can just dequeue scripts to make plugin AMP compatible.

**Comment by dshanske** [comment]
Is there a condition that would indicate it was an amp page? Like is_amp()

**Comment by milindmore22** [comment]
@dshanske yes, you can use either [is_amp_endpoint](https://amp-wp.org/reference/function/is_amp_endpoint/) or [amp_is_request](https://amp-wp.org/reference/function/amp_is_request/)

**Comment by dshanske** [comment]
Merged alternate version. Forgot about this when releasing 3.5.0.
