### ISSUE TITLE
Bad Request: Kind Menu Widget appends `/%year%/%monthnum%/`

### ISSUE THREAD

**Issue by bekopharm** [dshanske/indieweb-post-kinds#330]
Post Kinds is 3.5.1 
WordPress is 5.7
PHP is 7.4

Kind Menu appends `%year%/%monthnum%/` + TYPE to each link resulting in Bad Request:

![image](https://user-images.githubusercontent.com/5016428/110913813-e08fbb80-8315-11eb-9c54-7cecc587e0dc.png)

![image](https://user-images.githubusercontent.com/5016428/110913861-eeddd780-8315-11eb-97c9-e700a957db3d.png)

Adjusting the link by removing the doubled type and  `%year%/%monthnum%/` makes it work.

Example IS:

> /kind/article/%year%/%monthnum%/article/

Example SHOULD:

> /kind/article/

**Comment by bekopharm** [comment]
Workaround: Downgrade to Post Kinds 3.4.19 

I guess it's part of the 3.5.0 change `Removal of On This Day functionality to separate plugin`

What is this separate plugin? I can't find any new plugins of yours on WP.

**Comment by bekopharm** [comment]
Found `Tempus Fugit` but installting this didn't help so I guess I'll stick with `3.4.19` for now.

**Comment by dshanske** [comment]
The fix for this is already written, will deploy soon
