### ISSUE TITLE
 Trying to get property 'post_content' of non-object resulting in Bad Gateway

### ISSUE THREAD

**Issue by bekopharm** [dshanske/indieweb-post-kinds#331]
Post Kinds 3.4.19
PHP 7.4
WordPress 5.7

I get a bunch of Notices that result in a **Bad Gateway** eventually on _some_ pages:

> PHP message: PHP Notice:  Trying to get property 'post_content' of non-object in wp-content/plugins/indieweb-post-kinds/includes/class-kind-post-widget.php on line 104

> PHP message: PHP Notice:  Trying to get property 'post_excerpt' of non-object in wp-content/plugins/indieweb-post-kinds/includes/class-kind-post-widget.php on line 101

This seems to be some sort of loop because the trace is cut off after several repeats.

Works fine for more recent posts. This is from a very old post before the internals of Post Kinds changed.

**Comment by dshanske** [comment]
Resolved.
