### ISSUE TITLE
Undefined index in plugin?

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/indieweb-post-kinds#332]
WordPress: 5.7
Post Kinds: 3.5.2

I get emails with error messages from the server. The last couple of days I get messages like these:

`PHP Notice:  Undefined index: plugins in /kunder/incred_10722/diggin_13647/public/wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php on line 96
Notice: Undefined index: plugins in /kunder/incred_10722/diggin_13647/public/wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php on line 96
PHP Warning:  Invalid argument supplied for foreach() in /kunder/incred_10722/diggin_13647/public/wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php on line 96
Warning: Invalid argument supplied for foreach() in /kunder/incred_10722/diggin_13647/public/wp-content/plugins/indieweb-post-kinds/indieweb-post-kinds.php on line 96`

Any idea what I can do?

**Comment by dshanske** [comment]
That's interesting. That's the function that only hits when the plugin is upgraded. It's supposed to automatically activate any new rewrite rules. I'll check into it.
