### ISSUE TITLE
Possible Issue with Automattic's Export to Lightroom plugin

### ISSUE THREAD

**Issue by khurtwilliams** [dshanske/indieweb-post-kinds#333]
For several years, I have used [Automattic's Lightroom plugin](https://apps.wordpress.com/lightroom/) to export images directly to my Jetpack-powered WordPress website as part of my photo blogging workflow. Something went wrong last week.

![Screen Shot 2021-03-16 at 11 25 05 AM](https://user-images.githubusercontent.com/686971/111335228-97f43d00-864a-11eb-81fe-3c3bc782143f.JPEG)

I updated Jetpack to version 9.5 and WordPress to version 5.7 right before I started getting a Lightroom UI error. I removed and re-installed JetPack multiple times.

![Screen Shot 2021-03-16 at 11 25 09 AM](https://user-images.githubusercontent.com/686971/111335249-9cb8f100-864a-11eb-975c-e50e672da004.JPEG)

I worked with JetPack support to troubleshoot the issue, and we found this in my Apache error logs right after each attempt to use the Lightroom WordPress export plugin.

~~~

[Tue Mar 16 14:18:33.844440 2021] [php:error] [pid 19919] [client 192.0.100.246:23372] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($function) must be a valid callback, class Kind_Taxonomy does not have a method "wp_generate_attachment_metadata" in /var/www/html/wp-includes/class-wp-hook.php:294\nStack trace:\n#0 /var/www/html/wp-includes/plugin.php(212): WP_Hook->apply_filters()\n#1 /var/www/html/wp-admin/includes/image.php(631): apply_filters()\n#2 /var/www/html/wp-admin/includes/media.php(421): wp_generate_attachment_metadata()\n#3 /var/www/html/wp-content/plugins/jetpack/class.jetpack.php(3874): media_handle_upload()\n#4 /var/www/html/wp-content/plugins/jetpack/class.jetpack.php(3735): Jetpack->upload_handler()\n#5 /var/www/html/wp-includes/class-wp-hook.php(292): Jetpack->remote_request_handlers()\n#6 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()\n#7 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action()\n#8 /var/www/html/wp-admin/admin-ajax.php(202): do_action()\n#9 {main}\n  thrown in /var/www/html/wp-includes/class-wp-hook.php on line 294, referer: https://islandinthenet.com/wp-admin/admin-ajax.php?token=XXXXX%40PyLvJanXjoQTA%3A1%3A630&timestamp=1615904312&nonce=XXXXX&body-hash=XXXXXXXXXX%3D&signature=ggB%2BKU8S4eZrDQQj9ijS1uVCHg8%3D

~~~

There was an update to Post Kinds that I had applied before I updated JetPack 9.5 and WordPress 5.7. When I disable Post Kinds, the export from Lightroom to WordPress works, and I don't see the error.

**Comment by dshanske** [comment]
Will fix shortly..the error tells me what the problem is

**Comment by khurtwilliams** [comment]
Thank you for fixing this. It's all good now.

~ Khürt
