### ISSUE TITLE
Bulk Edit removed all Response properties

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/indieweb-post-kinds#338]
I have some PESOS posts from OwnYourSwarm. I did a bulk edit with all my posts tagged with 'checkin' to add those to the category 'Check-In'. After the bulk edit was completed, all the data in the response properties form above the content field were gone.

**Comment by dshanske** [comment]
Not sure about this one.

**Comment by troutcolor** [comment]
FWIW I saw the same sort of thing editing a bunch of posts in the All posts section adding a tag. Some of the posts were replies to tweets. later I found all the response properties gone. I did not notice at the time and didn't link the missing properties with the edit. 

I can replicated it by:
1. make a new post, add a url & title to the response properties.
2. save as draft
3. go to All Posts and do a quick edit, add a tag
4. edit post in classic editor, response properties are gone

Cheers
John

**Comment by scojjac** [comment]
Aha! This is what happened to me today. Did some bulk/quick edits (specifically, adding tags) on the All Posts screen and my response properties disappeared.

**Comment by dshanske** [comment]
I think I had better figure out a solution for this one. I turned off bulk changing kinds, but if it is somehow overwriting things...

**Comment by dshanske** [comment]
Resolved via 5e9e807a260217920fb6be8be8727e81449344cc
