### ISSUE TITLE
Not able to post/update new posts

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/indieweb-post-kinds#339]
Your current update don't let me post new stuff or edit existing ones anymore.

Fatal error: 
  Uncaught TypeError:
  array_map(): Argument #2 ($array) must be of type array, null given in [/.../wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php:433](https://github.com/dshanske/indieweb-post-kinds/blob/trunk/includes/class-kind-metabox.php#L433)
  Stack trace: 
    #0 /.../wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php(433):
  array_map() 
    #1 /.../wp-includes/class-wp-hook.php(305): Kind_Metabox::save_post()
    #2 /.../wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() 
    #3 /.../wp-includes/plugin.php(470): WP_Hook->do_action() 
    #4 /.../wp-includes/post.php(4468): do_action() 
    #5 /.../wp-includes/revision.php(334): wp_insert_post() 
    #6 /.../wp-includes/revision.php(190): _wp_put_post_revision() 
    #7 /.../wp-includes/class-wp-hook.php(305): wp_save_post_revision() 
    #8 /.../wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() 
    #9 /.../wp-includes/plugin.php(470): WP_Hook->do_action() 
    #10 /.../wp-includes/post.php(4442): do_action() 
    #11 /.../wp-includes/post.php(4570): wp_insert_post() 
    #12 /.../wp-admin/includes/post.php(423): wp_update_post() 
    #13 /.../wp-admin/post.php(227): edit_post() 
    #14 {main} 

thrown in /.../wp-content/plugins/indieweb-post-kinds/includes/class-kind-metabox.php on line 433

**Comment by chrisbergr** [comment]
is 'ifset' instead of 'isset' in this file legitimate?

**Comment by dshanske** [comment]
ifset is a function I created

**Comment by dshanske** [comment]
Will fix, a bit flummoxed last night m

**Comment by dshanske** [comment]
Should be fixed now.
