### ISSUE TITLE
Allow icons to be changed

### ISSUE THREAD

**Issue by davidized** [dshanske/indieweb-post-kinds#34]
Currently there isn't any way to change the icons being generated by kind_icon. It would be nice if there was a way to change them without needing to replace files or hack on the code.

I'll probably take a crack at this when I have a chance, but I wanted to make the suggestion in case others have thoughts on how it should be accomplished.

**Comment by dshanske** [comment]
Good idea. I just switched over from icon fonts to svg files. Haven't pushed any of the massive changes to stable yet. Stable being a release noted here and/or a WordPress.org push. Will add a filter before I do.

**Comment by davidized** [comment]
Awesome! I won't worry about tackling  it myself then.

**Comment by dshanske** [comment]
Version 2.3.0 is set to be released before year's end with everything I've been working on. If you look at the changelog, a lot of big changes came in that will set up a lot of future enhancements. If you have any issues fixable within the week, I'll add them in.

**Comment by dshanske** [comment]
Committed
