### ISSUE TITLE
Edit post kind descriptions

### ISSUE THREAD

**Issue by ScootRay** [dshanske/indieweb-post-kinds#340]
Hi,

I noticed I used to be able to edit descriptions, etc. of each Post Kind via the taxonomy admin menu (/wp-admin/edit-tags.php?taxonomy=kind) but for some reason it no longer shows the changed description. It looks like it is not saving it? 

Is there something additional I need to do to be able to edit descriptions of each kind?

Thanks!
Ray

**Comment by dshanske** [comment]
I can't reproduce this. Can you advise?

**Comment by dshanske** [comment]
Please reopen if you still have this issue.
