### ISSUE TITLE
Version 3.6.0 gives error with Micropub plugin

### ISSUE THREAD

**Issue by frankmeeuwsen** [dshanske/indieweb-post-kinds#346]
**Situation**: Testsite with only plugins installed: Indieauth, Micropub, Post Kinds (all latest version)
When I do a micropub POST call to my endpoint I get error 500, internal server error.
When I remove Post Kinds 3.6.0 and reinstall 3.5.12 everything works as it should
When I reinstall Post Kinds 3.6.0 I get the error again.

I have no other plugins installed, plain WordPress 6.0 with 2022 theme.

Please advice what to do.

**Comment by dshanske** [comment]
Anything in the logs that might help me figure this out?

**Comment by dshanske** [comment]
@frankmeeuwsen Willing to look at this, but need more info from the logs.

**Comment by frankmeeuwsen** [comment]
I tested again with version 3.6.3 and everything works fine now. No idea what went wrong 6 months ago.
