### ISSUE TITLE
[Bug] Parse this 500 error

### ISSUE THREAD

**Issue by asuh** [dshanske/indieweb-post-kinds#347]
I'm not sure what's causing it, but the following URL from The Verge is causing a 500 error.
https://www.theverge.com/2022/10/28/23428132/elon-musk-twitter-acquisition-problems-speech-moderation

**Comment by dshanske** [comment]
I found an error when I tried to parse this, which I fixed, dieectly from the Parse This package, which has its own Github repo. But no 500 error. So, I'll see if I need to refresh the bundled version.

**Comment by asuh** [comment]
Sounds good, let me know when I can test this out again.

**Comment by dshanske** [comment]
Should work now.
