### ISSUE TITLE
Blank $cite['summary'] in reads still outputs associated HTML

### ISSUE THREAD

**Issue by dtw** [dshanske/indieweb-post-kinds#350]
I have some "reads" with empty/blank `$cite['summary']` and this results in the following HTML output:

`<blockquote class="e-summary">::before</blockquote>`

I think I tracked this down to `views/kind-read.php`

`array_key_exists( 'summary', $cite )`

Shouldn't this check to see if there is anything in the summary before it prints the HTML wrapper?

**Comment by dshanske** [comment]
Resolved via 7f3d8b93681a1f07299cb617338f19182c82459c
