### ISSUE TITLE
Post Kinds not displayed in sidebar

### ISSUE THREAD

**Issue by brunopulis** [dshanske/indieweb-post-kinds#354]
I tried to add Post Kinds widget in my sidebar, but the Wordpress show this error:

> The "kind_menu_widget" block was affected by errors and may not work correctly.Check the developer tools for more details.

The error in develop tools. 

![image](https://github.com/dshanske/indieweb-post-kinds/assets/1204692/002829e4-d0dc-4c19-8869-0be902c2161d)

**Comment by dshanske** [comment]
Should be fixed in 3.7.3
