### ISSUE TITLE
Spurious additional line showing on Pages (as opposed to Posts)

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#36]
I'm still mostly relying on native WordPress Post Formats, though I'm leaning toward switching completely to post kinds (or figuring out how to straddle the two.) Though for the IndieWeb noobs, I'll mention what appears to be an odd conflict(?) between the two worlds.

Since the last one or two updates of Post-Kinds, there's a snippet of code somewhere that's adding an additional grey bar between the title and the content on them, specifically in WordPress "Pages", which probably shouldn't be happening as the native theme is more likely than not handling that output. See picture below: 

![post kinds](https://cloud.githubusercontent.com/assets/5882943/12693224/89916b08-c6b9-11e5-8d53-67024a5de7f9.PNG)

Deactivating Post-Kinds removes the additional bar `<hr>` (?), so it's definitely coming from code within the plugin. It appears to me to be hiding within
`<div class="e-content"><div class="h-cite response "></div><div class="entry-meta">`

The line doesn't appear to show up on blog posts marked as "article", "notes" or "photos", but does show up (with the appropriate icon) for posts marked as bookmark, favorite, like, listen, play, read, etc. (which is what I and others would presumably expect) Ex: http://boffosocko.com/2015/11/20/the-information-theory-of-life-quanta-magazine/

As most wouldn't expect it to show up on Pages, you might consider removing it from them in the next iteration.

In case it's necessary for troubleshooting purposes, I'm using Version 2.3.1 and in the settings I've not checked "Disable Post Formats".

**Comment by dshanske** [comment]
Fixed in development version. Will push to WordPress repository in future release. It now only shows context for the 'post' post type.
