### ISSUE TITLE
Issues with Rich Embeds

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#42]
With the oembed change in 4.4, the behavior is not as consistent as it was when this setting is enabled.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/42" class="u-in-reply-to"></a>Rich Embeds for silos like Twitter might actually be somewhat useful when using post kinds "like" and "repost" as the Twitter card would then display in the post in a nice visual fashion. The tougher question, however, is: Is the actual content of the Tweet being copied over as a blockquote with the full text (similar to what one would cut/paste from Twitter when clicking on their "embed" option within a Tweet) or is it using something like [embed]https://twitter.com/ChrisAldrich/status/707313378268618752 [/embed] which happens with the [IndieWeb Press This](https://github.com/pfefferle/wordpress-indieweb-press-this) plugin? If this is the case, then I imagine that if Twitter experienced a site-death then the proverbial "backup copy" of the plain text of the original liked/reposted tweet would be gone and the [embed] portion would be utterly useless thereafter, no?

Cross reference: http://techlifeweb.com/bookmarklets-for-indieweb-favorites-and-retweets/ and http://stream.boffosocko.com/2016/scott-i-love-the-concept-of-your-bookmarklets-and-how

**Comment by dshanske** [comment]
Fixed to a degree in the latest version, but more discussions to be had.
