### ISSUE TITLE
Problem with Previewing Post

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#49]
After adding data to "Post Properties" and attempting to Preview the post, I get the following error messages:

**Warning**: array_key_exists(): The first argument should be either a string or an integer in htdocs/folder/wp-content/plugins/indieweb-post-kinds/includes/class-kind-meta.php on line 197

**Warning**: Cannot modify header information - headers already sent by (output started at /htdocs/folder/wp-content/plugins/indieweb-post-kinds/includes/class-kind-meta.php:197) in /htdocs/folder/wp-includes/pluggable.php on line 1228

Occasionally I see issues like this from post-kinds when saving a draft or publishing as well.  It isn't a fatal error and the system seems to be saving the data properly and the final post always ultimately seems fine, but it would/could be daunting for new users.

Currently using the most recent WP.org Version 2.3.3 of the plugin.

**Comment by dshanske** [comment]
I put in an extra test for the scenario of no kind set. Will see if this pops up again.
