### ISSUE TITLE
IndieWeb and Android Mobile

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#52]
<a href="https://github.com/pfefferle/wordpress-indieweb-press-this/issues" class="u-in-reply-to"></a><a href="https://github.com/dshanske/indieweb-post-kinds/issues" class="u-in-reply-to"></a>IndieWeb and Android Mobile

@dshanske I remember you mentioning it briefly the other day and then saw something more specific this morning: http://indiewebcamp.com/irc/2016-05-03/line/1462285944410

Have you hacked around with either Bookmarklet Free or URL Forwarder apps from the Google Play store? They’re mentioned in the following two places:
https://snarfed.org/easy-indieweb-interactions-on-android 
http://stream.boffosocko.com/2016/sharing-from-the-indieweb-on-mobile-android-with-apps-and

I’d gotten URL Forwarder set up and configured to make mobile sharing for my WithKnown install to make bookmarking, sharing, reposting, and a few other functionalities work incredibly quickly and well.  I’ve put off doing so on WP since I have some other back-end dependencies that need tweaking so that I don’t create redundant loops with some of my other configuration.  With any luck one or the other will get you pretty far without having a full micropub application.

With these you can use Android’s ubiquitous sharing icon and share to one or the other of the apps which will do the URL scraping to be able to do some of the posting types you want. Depending on the output, you may need one or two additional tweaks, but it’ll give you a reasonable template for a workflow. I’m sure some further url parameters and integration could be put in to auto checking the correct post kind and thereby making your posts fully indieweb compatible on WP. Adding Indieweb Press This https://github.com/pfefferle/wordpress-indieweb-press-this/ functionality for bookmark, share, watching, listening, et al. would complete a larger cycle of functionality. 

Then, I’m sure there’s the additional functionality of API calls to Twitter/Facebook/etc. to implement the actual retweet/like on the native platform, but that could be handled later/separately (though Bridgy Publish might be able to handle this? I seem to remember a mention of it in the bookmarklet set up.)

Finally, if “Post Properties” could import the same URL and scrape the metadata, the entire process would be almost too simple and not need a “traditional” mobile app at all.

For URL Forwarder the base settings should be:
Reply: http://YOURSITENAME.com/wp-admin/press-this.php?v=8&type=reply&u=@url
Like: http://YOURSITENAME.com/wp-admin/press-this.php?v=8&type=like&u=@url 
Repost: http://YOURSITENAME.com/wp-admin/press-this.php?v=8&type=repost&u=@url 

Hopefully this gets you a few steps further on android mobile without a huge amount of work…

**Comment by dshanske** [comment]
Actually, I have put together something basic for the full post editor if you are interested.

http://YOURSITENAME.com/wp-admin/post-new.php?kind=bookmark&kindurl=@url 

Will automatically set the Kind and the URL on a new post. 

That other plugin which is now non-functional actually generated a simply Post Interface. I may refresh that one of these days for this purpose.
