### ISSUE TITLE
Add option to disable CSS

### ISSUE THREAD

**Issue by chrisbergr** [dshanske/indieweb-post-kinds#53]
Hi David,
it would be great if you add the option to disable css in the plugin's settings page. After your last change I was wondering, why all my post titles are hidden.. I'd also like to style post kinds like reply-to my own way. And even if I can disable it via hooks, it's just a cleaner way to have it in the settings. (Maybe I don't have access to the template code...)

**Comment by dshanske** [comment]
You can remove the style sheet with a single line of code. Or are you asking just for this specific design change?

**Comment by chrisbergr** [comment]
I'm asking for making the whole css file optional. And yes, I know how to remove it. But maybe some people don't or have no access to the php files, they're just able to add custom css via plugin. (multisite, provider,..)

**Comment by dshanske** [comment]
Will add option for it then. The reason I added the change that prompted this was for people who don't customize their themes. With the exception of maybe article, most of the post kinds don't have explicit titles.

**Comment by dshanske** [comment]
I split the admin CSS back from the entire CSS file, and have made an optional CSS file for theme compatibility. That would just leave the basic style on by default.
