### ISSUE TITLE
Pages get default kind

### ISSUE THREAD

**Issue by Ruxton** [dshanske/indieweb-post-kinds#54]
Any pages in my site are currently being set with the default kind (note).

Which means that I'm losing page titles on my pages.  Seeing as how kinds aren't even available to set on pages, can we either:

- Stop outputting kinds on pages; or
- Automatically set pages to 'article' kind; or
- Have a setting for the default kind for pages

Example of a page being marked up as a note - https://ignite.digitalignition.net/code/master-link-wordpress-plugin/

**Comment by dshanske** [comment]
Good point, didn't even consider this. Will adjust the auto set this week.

**Comment by dshanske** [comment]
Did a quick look. Can't reproduce this in testing. But am trying to figure out where it might be setting it. The custom taxonomy is set only for the 'post' type by default.

**Comment by dshanske** [comment]
There is a setting that sets the default kind if no kind is set. I've added a check to only set this if the post type is 'post'. If there is demand for setting kinds for pages or custom post types, I'll like to that in the future as a separate issue.

**Comment by Ruxton** [comment]
@dshanske yeap that works, cheers!.
