### ISSUE TITLE
Support Post Kind: Recipe

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#57]
I've been playing around with food recipes lately and thought this might be another worthwhile/relatively common post type (https://indieweb.org/recipe) to add/have in the future along with food and drink. 

I'll also note that WordPress (via JetPack) just updated their recipe shortcode: https://en.support.wordpress.com/recipes/ which 
gives some additional front end support (as well as mf1 mark up for hrecipe, though I'll see what I can do to inject mf2 as well)

Potential icons:
Fontawesome: &lt;i class="fa fa-cutlery" aria-hidden="true"></i>
Genericon: ?? 

Use case example: http://boffosocko.com/2016/07/17/chili-prep-for-dinner-tonight/

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/57" class="u-in-reply-to"></a>I've added mf2 classes to WordPress's [recipe] shortcode at: https://github.com/chrisaldrich/jetpack/pull/1/commits/f914ebe3bd573d1d6d42c5b7752bf26c41448a3b

I've also opened an issue for the JetPack repository to see if they'll include it moving forward.

**Comment by dshanske** [comment]
Recipe is worthwhile, but the amount of data means it will be hard to add to the post UI. I will reserve the term, as I have for other terms for now.
