### ISSUE TITLE
Stylable CSS classes

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#60]
Is it me being crazy, or are all the classes on the data here just semantic? 

For front end developers, it would be nice if you included some plugin-wide classes (or ids) to allow easier styling of individual post kinds, particularly since we all know styling on microformats is a bad idea... ;)

Maybe pk-like, pk-bookmark, etc. for the "titles" and a class on the blockquote as well?  It seems odd to me that the title is smaller than my default blockquote font, but there isn't anything non-semantic to style on... 

![css classes](https://cloud.githubusercontent.com/assets/5882943/17385396/4582ec04-5997-11e6-86ed-b6aba26b7121.PNG)

**Comment by dshanske** [comment]
kind-note and such are already in the post class.

**Comment by dshanske** [comment]
This should be addressed by the kind-{type}.
