### ISSUE TITLE
Defaulting to 'note' causes title to vanish when importing

### ISSUE THREAD

**Issue by kevinmarks** [dshanske/indieweb-post-kinds#62]
If Post Kinds is installed when importing old posts, it sets the kind to note on creation, because of the defaults. This leads to the titles being hidden.

There are a combination of things going awry here - if a post kind wasn't set, leaving it unset is probably a good idea. I'm not sure which default is going wrong, whether it is micropub_set_kind()
https://github.com/dshanske/indieweb-post-kinds/blob/e45f65d4dcc009e3b05bde7cd2c43ddee30d9875/includes/class-kind-taxonomy.php#L581

Which doesn't check if title and content are equal per post-kinds (otherwise should be article, not note)

or the default choice of 'note' bieng written back.

To fix this I had to do

```
DELETE FROM `wp_term_relationships` WHERE `wp_term_relationships`.`term_taxonomy_id` = 37
```

**Comment by dshanske** [comment]
This shouldn't happen anymore.
