### ISSUE TITLE
UI: Duration doesn't make sense in Read post kind

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#65]
When making a "Read" post in which data exists in the "time" tab for published dt and updated dt, the output displays more like one would anticipate with a music post type (or jam, listen, play, watch, travel) using start/end vocabulary instead and outputting a "Duration".  

Duration may make sense if one were doing a start/end time for their reading, but then the scraper shouldn't be automatically pulling in the publish/update dates/times. Personally I'd prefer to let the publication time of my post indicate when the thing was read and have Post Kinds indicate the publication of the original piece I was reading.

Possibly better would be an if/then statement to differentiate types and for Read types outputting a date/time for the original publication and/or potentially an updated date/time if it exists.

At present, the issue is most common on New York Times posts for which the scraper pulls in the correct metadata. 

Example: http://boffosocko.com/2016/11/14/chris-aldrich-is-reading-facebook-restores-iconic-vietnam-war-photo-it-censored-for-nudity/ 
![duration](https://cloud.githubusercontent.com/assets/5882943/20466247/6e5f67aa-af24-11e6-9d57-f83c3928163f.PNG)

For a small portion of IndieWeb sites, the scraper is returning data in these fields that are identical for both the published and updated fields which returns an odd duration result as well.  (See: http://boffosocko.com/2016/11/11/chris-aldrich-is-reading-fragmentions-for-poets/) Perhaps if the date/time in both fields are identical, there could be some error checking to prevent a spurious output since published shouldn't equal updated.

**Comment by dshanske** [comment]
Published and Updated do use the same fields as start and end in the interface but not in the database. I will think on changes.

**Comment by dshanske** [comment]
UI split for this completed in branch link-preview. Merging to master soon.
