### ISSUE TITLE
Retrieve Running Time for listen and watch post kinds?

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#71]
For sites like Soundcloud, ITunes, Netflix, youtube (if it's available) it would be nice to retrieve the "running time" of the music, show, film, etc. to display as a running time in the UI for listen, watch, and jam types (rather than the published/updated) for other post types.

Sample URLs
https://www.netflix.com/watch/60002321?trackId=14170060&tctx=1%2C1%2C711b329a-1ca8-4c14-b4d7-43f682113d2e-14372159
https://www.youtube.com/watch?v=FNr0JNwsLy8
https://soundcloud.com/user-154380542/how-to-build-an-autocracy-david-frum-the-atlantic-march-2017
https://open.spotify.com/track/3B3ZOmLGFlAjyBKHbgiblv
https://www.hulu.com/watch/403538
WordPress blueberry podcasts: http://www.eatthispodcast.com/long-live-the-carolina-african-runner/

When not scrape-able, allowing one to simply enter a 0:00:00 time and a finish time and letting it display the appropriate running time (without entering a date) would be useful for these types as well. (I'm presuming it requires dates to calculate currently as I haven't yet checked....)

**Comment by dshanske** [comment]
Addressed, though not in scraping yet

**Comment by dshanske** [comment]
I have this for Youtube and Soundcloud. I don't see the data on Spotify, Netflix, or Hulu to get. The podcast has no marked up duration parameter either.
