### ISSUE TITLE
Image samples in readme broken

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#73]
From IRC Chat: https://chat.indieweb.org/2017-02-22/1487723001233000
# 16:23 techlifeweb GWG: the screenshots are broken here https://github.com/dshanske/indieweb-post-kinds/blob/master/readme.md

GWG, Unless you have specifics in mind, I'll find something appropriate and fix these via PR later tonight when I'm back home.

**Comment by dshanske** [comment]
They relate to the WordPress.org repo, but I should update them after the current changes are done.

**Comment by dshanske** [comment]
@chrisaldrich Do you want to contribute some nice screenshots?

**Comment by dshanske** [comment]
Fixed
