### ISSUE TITLE
Notes on Post Kinds mapping to Post Formats

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#74]
Recently there was some discussion in IRC of how [Post Kinds](https://github.com/dshanske/indieweb-post-kinds) map onto [Post Formats](https://developer.wordpress.org/themes/functionality/post-formats/) for those who happen to use both. There was a suggestion that when setting the kind via bookmark or URL string, that the Format could also be set automatically (though I don't recall anyone coming up with a URL string to set it). 

In the case that this is automatically preset in the future (via bookmarklet or other means), or even just for reference (in which case close the issue), the following is a list of all the current Post Kinds and the Post Formats to which I typically do/would map them onto each other in actual practice.  Those in bold are ones which have a simple 1-to-1 mapping.

# The Non-Response Kinds
Article - Standard
Note - Status
**Photo - Photo** (also Gallery for more than one)

# The Response Kinds
Reply - Status
Repost - Link (possibly Status in rare instances)
Like - Link
Favorite - Link
Bookmark - Link
**Quote - Quote** (also maybe Chat, but rare)

Listen - scrobble - Audio 
Jam - Audio 
Watch - Video (when embedding video into the post), otherwise Status
Play - Status
Read - Link (if it's an online article which I link to, similar to a bookmark), otherwise Status if it's an unlinkable physical book/magazine

# Reserved
Wish - Link (if it's in an online store), otherwise, more rarely Status
Weather - Status
Exercise - Status
Trip - Status (this is a weak link)
Itinerary - Status (this is a weak link)
Check-In - Status
Tag - Link??
RSVP - Status
Event - Link / maybe Status depending on context
Food - Status
Drink - Status
Follow - Link / Status depending on intent, but usually Link
Mood - Status
Recipe - Standard?? (this is a weak link)

# Generally Unused Post Formats in overlap with Post Kinds:
 Aside 
 Chat

**Comment by dshanske** [comment]
Implemented partially
