### ISSUE TITLE
No Post Kinds meta box w/ v2.5.0

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#76]
So I updated my production server (running WP 4.7.2) with the new stable version 2.5.0 (from the WP.org rather than the Github which I also couldn't get working a few days ago) and see all the new changes, but for some reason I'm still not seeing the Post Kinds Meta box to let me choose the Post Kind for the particular post.

I spun up a new site  with no plugins other than the required IndieWeb + Post Kinds and I'm seeing the same thing. 

Any thoughts on why it might not be registering/displaying? I'm at a loss after having thought about it and trying to trouble shoot it for the past couple of days. Also a bit worried that new users will be at a complete loss...

While I'm thinking about it, and in some part because of this particular issue, I'm wondering why have two separate UI boxes (one to choose the kind and another to input/modify the meta-data)? As things stand, I can easily see great arguments for keeping them separate, so don't change things just because I've mentioned it. Though if you do modify things via JS later so that choosing the kind limits the post properties displayed based on the post kind, then having the two UI pieces either combined or more closely linked will be far more intuitive for the user.

**Comment by dshanske** [comment]
This is very strange, because both @miklb and I were seeing it There was a change made to how the box was loaded to remove some duplicative code. But that shouldn't explain this.

**Comment by dshanske** [comment]
I tried installing it on another site. The box is there.

**Comment by devilgate** [comment]
I've got this problem too. Just as another data point for you. There's a tabbed box where I can put in links and author details and such. But there's nowhere that lets you select a post kind.

The posts still have a  kind after they're created, though. And the setting for the default kind affects that. So I've changed it so the default is now article, for example. But the only way to influence the kind is to change the post format.

**Comment by dshanske** [comment]
This is a problem I have yet to figure out. I may ask either of you to try a test version to see if I can figure out why.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/76#issuecomment-287464489" class="u-in-reply-to"></a>@dshanske Always happy to give it a shot...

**Comment by dshanske** [comment]
Resolved with latest push.
