### ISSUE TITLE
No Checkin option with Simple Location installed.

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#78]
I notice that the commented line 189 of https://github.com/dshanske/indieweb-post-kinds/blob/a59b0458fb6ca2ded4fccf6de2f917730c9fa1ee/includes/class-kind-taxonomy.php is still in the code, but the chunk of code that used to be under it is gone...

Though I've got simple location installed, the checkbox for enabling checkins doesn't appear in the settings page so that I can select it.  Did that chunk of code move or disappear? Bug perhaps? Or do we still have to go in and manually tweak it to get checkin to appear as an option if it's "hidden"?

v2.5.1 on WP v4.7.2

**Comment by dshanske** [comment]
Pending rewrite

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/78#issuecomment-287580079" class="u-in-reply-to"></a>I suspect I'd previously just deleted checkin from the line
`$hide = array( 'note', 'weather', 'exercise', 'travel', 'itinerary', 'tag', 'follow', 'drink', 'eat', 'trip', 'checkin', 'recipe', 'mood' );`
in /includes/class-kind-config.php

**Comment by miklb** [comment]
@dshanske per our discussion here's a XML export of a test OYS checkin.

Let me know if a sql dump would be more beneficial.


Note, GitHub doesn't allow XML attachments, so I used .txt you can just swap it back to .xml 

[ownyourswarm_test_data.txt](https://github.com/dshanske/indieweb-post-kinds/files/1091791/ownyourswarm_test_data.txt)

**Comment by dshanske** [comment]
The Checkin option will be available in 2.7.0, but no UI yet.
