### ISSUE TITLE
Post Kinds adds kind-note to mark up on pages

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#79]
I would only expect that post kinds would add kind mark up to posts of particular kinds and not on pages.

As an example, here's what I'm seeing on what is a page and not a post:
`<article id="post-55672667" class="post-55672667 page type-page status-publish hentry kind-note">`
In particular, it's adding `kind-note` to the classes for this page.

Was this by design or accident?

**Comment by dshanske** [comment]
Accident, likely. Will look

**Comment by dshanske** [comment]
Addressed in development branch.
