### ISSUE TITLE
Retrieve button failing

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#80]
In a handful of tests today, the retrieve button doesn't seem to be working properly using Post Kinds v2.5.1 WP v4.7.2+

I'm seeing this on a variety of sources including the following:
https://www.nytimes.com/2017/02/21/business/economy/kenneth-arrow-dead-nobel-laureate-in-economics.html?_r=0
https://wired.com/2017/03/ben-carson-just-got-whole-lot-wrong-brain/
https://theatlantic.com/science/archive/2017/03/how-to-gut-the-epa-in-the-name-of-honesty/519462?utm_source=atltw
http://economist.com/news/leaders/21718516-spread-exotic-grains-evidence-globalisation-works-praise-quinoa

The console is giving long error messages which all start with:
`Uncaught TypeError: Cannot use 'in' operator to search for 'name' in `
I'll include a sample complete error below. 

Did recent tweaks to it cause it to go wonky? I know it was working better than the prior version when I'd tested the branch version of it just before you released 2.5.0. Now it doesn't seem to be working at all on any sources.

I tried it on a new/clean install with a minimal set of plugins and didn't see the same issue there (fortunately).

Thoughts on what may be causing this? I've tried uninstalling/reinstalling. Disabling other plugins, etc...

`Uncaught TypeError: Cannot use 'in' operator to search for 'name' in {"name":"Kenneth Arrow, Nobel-Winning Economist Whose Influence Spanned Decades, Dies at 95","summary":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","author":"https:\/\/www.nytimes.com\/by\/michael-m-weinstein","publication":"nytimes.com","published":"2017-02-21T21:40:51-05:00","updated":"2017-02-22T11:21:49-05:00","category":["Deaths (Obituaries)","Economics (Theory and Philosophy)","Nobel Prizes","Obituary","Economics","Nobel Prize"],"photo":["https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-facebookJumbo.jpg","https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-videoSixteenByNineJumbo1600.jpg","https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-master768.jpg","https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-2\/22arrow-obit-2-master675.jpg"],"raw":{"description":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","url":"https:\/\/www.nytimes.com\/2017\/02\/21\/business\/economy\/kenneth-arrow-dead-nobel-laureate-in-economics.html","type":"article","title":"Kenneth Arrow, Nobel-Winning Economist Whose Influence Spanned Decades, Dies at 95","published":"2017-02-21T21:40:51-05:00","modified":"2017-02-22T11:21:49-05:00","section":"Economy","author":"https:\/\/www.nytimes.com\/by\/michael-m-weinstein","tag":["Deaths (Obituaries)","Economics (Theory and Philosophy)","Nobel Prizes","Obituary","Economics","Nobel Prize"],"unfiltered":{"viewport":"width=device-width, initial-scale=1, maximum-scale=1","sourceApp":"nyt-v5","applicationName":"article","al:android:url":"nytimes:\/\/reader\/id\/100000003849524","al:android:package":"com.nytimes.android","al:android:app_name":"NYTimes","twitter:app:name:googleplay":"NYTimes","twitter:app:id:googleplay":"com.nytimes.android","twitter:app:url:googleplay":"nytimes:\/\/reader\/id\/100000003849524","al:iphone:url":"nytimes:\/\/www.nytimes.com\/2017\/02\/21\/business\/economy\/kenneth-arrow-dead-nobel-laureate-in-economics.html","al:iphone:app_store_id":"284862083","al:iphone:app_name":"NYTimes","al:ipad:url":"nytimes:\/\/www.nytimes.com\/2017\/02\/21\/business\/economy\/kenneth-arrow-dead-nobel-laureate-in-economics.html","al:ipad:app_store_id":"357066198","al:ipad:app_name":"NYTimes","robots":"noarchive","hdl_p":"Kenneth Arrow, Influential Economist and Nobel Laureate, Is Dead at 95","description":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","genre":"Obituary (Obit)","articleid":"100000003849524","usageTerms":"http:\/\/www.nytimes.com\/content\/help\/rights\/sale\/terms-of-sale.html","hdl":"Kenneth Arrow, Nobel-Winning Economist Whose Influence Spanned Decades, Dies at 95","pdate":"20170221","utime":"20170222112149","ptime":"20170221214051","DISPLAYDATE":"Feb. 21, 2017","dat":"Feb. 21, 2017","lp":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","msapplication-starturl":"http:\/\/www.nytimes.com","cre":"The New York Times","slug":"22arrow","article:collection":"https:\/\/static01.nyt.com\/services\/json\/sectionfronts\/business\/economy\/index.jsonp","sectionfront_jsonp":"https:\/\/static01.nyt.com\/services\/json\/sectionfronts\/business\/economy\/index.jsonp","og:url":"https:\/\/www.nytimes.com\/2017\/02\/21\/business\/economy\/kenneth-arrow-dead-nobel-laureate-in-economics.html","og:type":"article","og:title":"Kenneth Arrow, Nobel-Winning Economist Whose Influence Spanned Decades, Dies at 95","og:description":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","article:published":"2017-02-21T21:40:51-05:00","article:modified":"2017-02-22T11:21:49-05:00","article:section":"Economy","article:section-taxonomy-id":"104D1E63-9701-497B-8CF4-A4D120C9014E","article:section_url":"https:\/\/www.nytimes.com\/pages\/business\/index.html","article:top-level-section":"business","fb:app_id":"9869919170","twitter:url":"https:\/\/www.nytimes.com\/2017\/02\/21\/business\/economy\/kenneth-arrow-dead-nobel-laureate-in-economics.html","twitter:title":"Kenneth Arrow, Nobel-Winning Economist Whose Influence Spanned Decades, Dies at 95","twitter:description":"Professor Arrow, one of the most brilliant minds in his field during the 20th century, became the youngest economist ever to earn a Nobel at the age of 51.","author":"Michael M. Weinstein","tone":"news","byl":"By MICHAEL M. WEINSTEIN","PT":"article","CG":"business","SCG":"economy","PST":"Obituary (Obit)","tom":"Obituary (Obit)","edt":"NewYork","og:image":"https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-facebookJumbo.jpg","twitter:image:alt":"Kenneth J. Arrow receiving the Nobel Memorial Prize in Economic Science in Stockholm in 1972.","twitter:image":"https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-videoSixteenByNineJumbo1600.jpg","article:author":"https:\/\/www.nytimes.com\/by\/michael-m-weinstein","article:tag":"Nobel Prizes","des":"Nobel Prizes","keywords":"Deaths (Obituaries),Economics (Theory and Philosophy),Nobel Prizes","news_keywords":"Obituary,Economics,Nobel Prize","thumbnail_150":"https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-thumbLarge.jpg","thumbnail_150_height":"150","thumbnail_150_width":"150","thumbnail":"https:\/\/static01.nyt.com\/images\/2017\/02\/22\/us\/22arrow-obit-1\/22arrow-obit-1-thumbStandard.jpg","thumbnail_height":"75","thumbnail_width":"75","dfp-ad-unit-path":"business\/economy","dfp-amazon-enabled":"false"},"site_name":"nytimes.com"}}
    at Object.success (retrieve.js:14)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at y (load-scripts.php:4)
    at XMLHttpRequest.c (load-scripts.php:4)`

**Comment by dshanske** [comment]
Can you check the developer console in Chrome or Firefox to see if the javascript has an error?

**Comment by miklb** [comment]
I'm getting a similar error when attempting to retrieve post properties

JS Console
`Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)`

`https://miklb.com/wp/wp-json/link-preview/1.0/parse/?kindurl=`

Possibly due to being on https?

**Comment by dshanske** [comment]
My test site is on https actually. That created a problem for @chrisaldrich in another plugin

**Comment by miklb** [comment]
A little more info:

I set my permalink to default, and the nondescript pop-up error went away. Now getting a `https://twitter.com/maggieNYT/status/846753341170487297 TypeError: response is not an Object. (evaluating ''name' in response')`

line 9 response.js `if ( 'name' in response ) {`

**Comment by miklb** [comment]
Also potentially related, but says fixed in 4.7.3

https://core.trac.wordpress.org/ticket/39432

**Comment by miklb** [comment]
So trying to do some more debugging on this on my end, I have WordPress installed in a subdirectory. If I remove the `/wp/` from the 404 URL, and test that with curl, I get a 403, if I test it in the browser I'm logged into WP with I get
```
{"code":"rest_missing_callback_param","message":"Missing parameter(s): kindurl","data":{"status":400,"params":["kindurl"]}}
```
I'm testing some nginx configs for WP to see if that's where the issue ultimately lies, but any suggestions welcome.

**Comment by miklb** [comment]
@chrisaldrich not sure our errors are related, but I am seeing some suggestions to reset permalinks, especially if using Apache.

**Comment by dshanske** [comment]
That would be explain why I never saw it, but will be explored

**Comment by miklb** [comment]
As I mentioned in IRC, my local install works, but I am now seeing this warning in my `debug.log` on local install
```
PHP Warning:  array_values() expects parameter 1 to be array, null given in /Users/miklb/Dev/miklb.dev/content/plugins/indieweb-post-kinds/includes/class-parse-this.php on line 701
```

**Comment by dshanske** [comment]
I am going to be looking at the whole chain that converts a URL to parsed properties

**Comment by miklb** [comment]
More follow up:

I was able to reproduce my issue locally. I have WordPress in /wp but serve the site from root so I get a 404 error on the wp-json URL. If I set permalink to default, then I get the `response is not an object` error for line 14 in `response.js`. 

Looking at nginx config again.

**Comment by miklb** [comment]
Resolved for me in 2.5.2 branch

If anyone else experiences this with https, make sure your WP & Site URL are also set to https, otherwise can get a 403 error.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/80" class="u-in-reply-to"></a>This has been driving me crazy, so I stripped everything down and rebuilt from scratch. I'm not sure why it didn't show up before when I previously cycled through other plugins as the potential cause/conflict, but it appears that Automattic's [WP Super Cache ](https://wordpress.org/plugins/wp-super-cache/) when activated and with caching turned on in the settings admin is what is causing my initial issue. 

Turning caching off on this particular plugin (or un-activating it altogether) allows the retrieve button to work properly. My JS skills are woeful and I'm not seeing anything on direct inspection that would cause this problem when it's enabled. If anyone has useful thoughts about the conflict, I'd love to hear them. 

It appears that WP Super Cache hasn't updated since October, so it likely wasn't a change on their end, but rather a change when Post Kinds upgraded.

**Comment by dshanske** [comment]
Can I close this though?

**Comment by chrisaldrich** [comment]
Yes, it's generally working better based on my recent tests.
