### ISSUE TITLE
Notice: Undefined index for bookmark/photo kinds

### ISSUE THREAD

**Issue by ngm** [dshanske/indieweb-post-kinds#85]
I get this error for posts with bookmark or photo types:

> Notice: Undefined index: name in /var/www/.../wp-content/plugins/indieweb-post-kinds/includes/class-kind-view.php on line 246

No problem with notes or articles.

**Comment by dshanske** [comment]
I am going to be checking out some bug reports and making some changes in the coming days

**Comment by ngm** [comment]
I realised that for bookmarks, the error was appearing because I did not have a value set for `Post Properties -> Main -> Name/Title` (or the URL field, in fact.)  

These values don't get set if you create a bookmark via Micropub.

**Comment by ngm** [comment]
The same is true when using the Photo kind/Image format.

It's not clear to me why I need to set both the Post Title and then Name/Title in Post Properties?

**Comment by dshanske** [comment]
One is the title of the post, the other the title of what it is referring to. In a photo post, there wouldn't necessarily be a different​ one.

**Comment by dshanske** [comment]
I need to tweak the logic on this clearly.

**Comment by dshanske** [comment]
Did a temporary fix. But I need a better one.
