### ISSUE TITLE
Auto-setting of post formats isn't being triggered when the post is created by Micropub

### ISSUE THREAD

**Issue by ngm** [dshanske/indieweb-post-kinds#87]
If I create a new post via the Wordpress inferface, and set the post kind of 'Note', it automatically gets given the post format of 'Aside'.  This is correct.

If I create a note via Micropub (e.g. Quill), the newly created post gets a post kind of 'Note', but a post format of 'Standard'.  The expected post format is 'Aside'.

The same problem also occurred with a Bookmark created via Micropub.  It had the correct post kind ('Bookmark'), but the wrong post format ('Standard').

**Comment by dshanske** [comment]
Should be resolved in latest development branch.
