### ISSUE TITLE
Some template quirks

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#97]
For most kinds, the "Author/Artist name" isn't wrapped with the "Author/Artist URL" unless there is also an author photo. It should be wrapped even if the photo doesn't exist.

For the read kind, the "Site Name/Publication/Album" doesn't have a closing parenthesis
example: http://boffosocko.com/2017/06/13/the-indieweb-movement-will-help-people-control-their-own-web-presence-future-hosting/

For photos, the posts are duplicating the photo in the body for me now. Additionally the previously included titles, which I'd had in "Name/Title" field of Post Properties isn't showing anymore. The previous default was a better simple template.

**Comment by dshanske** [comment]
I'll address the title issue. The auto embedding was designed based on the complaints re ownyourgram and such not working properly. I have to issue a few changes anyway.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/indieweb-post-kinds/issues/97" class="u-in-reply-to"></a>The missing close parenthesis should be on line 72 before the closing em tag in at https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/views/kind.php

Thus:
<code>echo '&lt;em&gt; (' . $site_name . ')&lt;/em&gt;';</code>
